&PARAM_TEST
  NprcX = 2, 
  NeGX  = 8, 
  NprcY = 2, 
  NeGY  = 8, 
  NeGZ  = 1, 
  PolyOrder = 7,
/
&PARAM_Poisson3D_MG
  !- h-MG
  H_LEVEL_NUM = 0, 
  NeGX_list = 8, 4,
  NeGY_list = 8, 4,  
  NeGZ_list = 1, 1,  
  !- p-MG
!  P_LEVEL_NUM = 3,
!  P_LEVEL_LIST = 7, 3, 1,
  P_LEVEL_NUM = 3,
  P_LEVEL_LIST = 7, 3, 1, 
  !- V-cycle parameters
  MG_Vcyc_Num_Max = 20,
  MG_Threshold_Ratio_Residual_L2 = 1D-6,
  MG_Threshold_Residual_L2  = 1D-12,
  MG_Threshold_Residual_Max = 1D-12,
/
&PARAM_MGSmoother
  num_smooth_itr_max          = 5,
  residual_threshold_ratio_l2 = 1D-2,
  residual_threshold_l2       = 1D-8,
  residual_threshold_max      = 1D-8,
  history_residual_step       = 1,
  !- Solver for elementwise problems
  elem_solver                    = 'PCG', !'DIRECT',
  !- For preconditioned conjugate gradient method
  num_smooth_itr_max_internal    = 50,
  residual_threshold_l2_internal = 1D-3,
/
&PARAM_TIME
  TIME_DURATION                 = 1D0, 
  TIME_DURATION_UNIT            = 'SEC', 
  TIME_DT                       = 1D0, 
  TIME_DT_UNIT                  = 'SEC', 
/
&PARAM_FILE_HISTORY
 FILE_HISTORY_DEFAULT_BASENAME  = "history",
 FILE_HISTORY_DEFAULT_TINTERVAL = 1D0,
 FILE_HISTORY_DEFAULT_TUNIT     = "SEC",
 FILE_HISTORY_DEFAULT_TAVERAGE  = .false.,
 FILE_HISTORY_DEFAULT_DATATYPE  = "REAL8",
 FILE_HISTORY_OUTPUT_STEP0      = .true.,
/
&HISTORY_ITEM name='q'         /
&HISTORY_ITEM name='qexact'    /
&HISTORY_ITEM name='f'         /
