################################################################################
#
# Makefile for each test program
#
################################################################################

PWD         = $(shell pwd)
TOPDIR      = $(abspath ../../../..)
FELIB_TEST_DIR = ../../

BINNAME = test_linkedlist
OBJS    =

RUNCONF         = 
TPROC           = 1
OMP_NUM_THREADS = 1

#------------------------------------------------------
include $(FELIB_TEST_DIR)/Makefile.common
