!-------------------------------------------------------------------------------
! Warning: This file was generated from mod_timeint_rk.f90.erb.
!          Do not edit this file.
!-------------------------------------------------------------------------------
!-------------------------------------------------------------------------------
#include "scaleFElib.h"
module mod_timeint_rk
  !-----------------------------------------------------------------------------
  !
  !++ Used modules
  !
  use scale_precision
  use scale_io
  use scale_prc
  use scale_prof

  !-----------------------------------------------------------------------------
  implicit none
  private

  !-----------------------------------------------------------------------------
  !
  !++ Public type, procedures
  !
  type, public :: timeint_rk
    real(RP) :: dt

    integer :: rk_scheme_id
    integer :: var_num
    integer, allocatable :: size_each_var(:)
    integer :: nstage
    integer :: tend_buf_size

    real(RP), allocatable :: coef_a(:,:)
    real(RP), allocatable :: coef_b(:)
    real(RP), allocatable :: coef_c(:)

    integer, allocatable :: tend_buf_indmap(:)
    real(RP), allocatable :: tend_buf1D(:,:,:)
    real(RP), allocatable :: var0_1D(:,:)
    real(RP), allocatable :: varTmp_1D(:,:)    
    real(RP), allocatable :: tend_buf2D(:,:,:,:)
    real(RP), allocatable :: var0_2D(:,:,:)
    real(RP), allocatable :: varTmp_2D(:,:,:)    
    real(RP), allocatable :: tend_buf3D(:,:,:,:,:)
    real(RP), allocatable :: var0_3D(:,:,:,:)
    real(RP), allocatable :: varTmp_3D(:,:,:,:)    

    logical :: low_storage_flag
    integer :: ndim
  contains
    procedure :: Init => timeint_rk_Init
    procedure :: Final => timeint_rk_Final
    procedure :: Advance1D => timeint_rk_advance1D
    procedure :: Advance2D => timeint_rk_advance2D
    procedure :: Advance3D => timeint_rk_advance3D
    generic :: Advance => Advance1D, Advance2D, Advance3D
  end type

  !-----------------------------------------------------------------------------
  !
  !++ Public parameters & variables
  !
  !-----------------------------------------------------------------------------
  !
  !++ Private procedures
  !
  !-------------------

  integer, parameter :: RK_SCHEME_TVD_3 = 1

contains

!----------------

  subroutine timeint_rk_Init( this,  &
    rk_scheme_name, dt, var_num, size_each_var )
    
    class(timeint_rk), intent(inout) :: this
    character(*), intent(in) :: rk_scheme_name
    real(RP), intent(in) :: dt
    integer, intent(in) :: var_num
    integer, intent(in) :: size_each_var(:)

    !----------------------------------------

    this%dt = dt
    this%ndim = size(size_each_var)
    this%var_num  = 1
    allocate( this%size_each_var(this%ndim) )
    this%size_each_var(:) = size_each_var(:)

    select case(rk_scheme_name)
    case('RK_4')
      this%nstage = 4
      this%tend_buf_size = 1
      this%low_storage_flag = .false.
    case('RK_TVD_2')
      this%nstage = 2
      this%tend_buf_size = 1
      this%low_storage_flag = .true.
    case('RK_TVD_3')
      this%nstage = 3
      this%tend_buf_size = 1
      this%low_storage_flag = .true.
    case default
      LOG_ERROR("timeint_rk_Init",*) trim(rk_scheme_name)//' is not supported. Check!'
      call PRC_abort
    end select

    allocate ( this%coef_a(this%nstage,this%nstage), this%coef_b(this%nstage), this%coef_c(this%nstage) )
    select case(this%ndim)
    case(1)
      allocate( this%tend_buf1D(size_each_var(1), var_num, this%tend_buf_size) )
      allocate( this%var0_1D(size_each_var(1), var_num) )
      if (.not. this%low_storage_flag) allocate( this%varTmp_1D(size_each_var(1), var_num) )        
    case(2)
      allocate( this%tend_buf2D(size_each_var(1),size_each_var(2), var_num, this%tend_buf_size) )
      allocate( this%var0_2D(size_each_var(1),size_each_var(2), var_num) )
      if (.not. this%low_storage_flag) allocate( this%varTmp_2D(size_each_var(1),size_each_var(2), var_num) )        
    case(3)
      allocate( this%tend_buf3D(size_each_var(1),size_each_var(2),size_each_var(3), var_num, this%tend_buf_size) )
      allocate( this%var0_3D(size_each_var(1),size_each_var(2),size_each_var(3), var_num) )
      if (.not. this%low_storage_flag) allocate( this%varTmp_3D(size_each_var(1),size_each_var(2),size_each_var(3), var_num) )        
    end select
    allocate( this%tend_buf_indmap(this%nstage) )

    this%coef_a(:,:) = 0.0_RP
    this%coef_b(:) = 0.0_RP
    this%coef_c(:) = 0.0_RP

    select case(rk_scheme_name)
    case('RK_4')
      this%coef_a(2,1) = 0.5_RP
      this%coef_a(3,2) = 0.5_RP
      this%coef_a(4,3) = 1.0_RP
      this%coef_b(:) = (/ 1.0_RP, 2.0_RP, 2.0_RP, 1.0_RP /)/6.0_RP
      this%tend_buf_indmap(:) = 1
    case('RK_TVD_2')
      this%coef_a(1,1) = 1.0_RP
      this%coef_a(2,2) = 0.5_RP
      this%tend_buf_indmap(:) = 1
    case('RK_TVD_3')
      this%coef_a(1,1) = 1.0_RP
      this%coef_a(2,2) = 1.0_RP/4.0_RP
      this%coef_a(3,3) = 2.0_RP/3.0_RP
      this%tend_buf_indmap(:) = 1
    end select
    return
  end subroutine timeint_rk_Init

  subroutine timeint_rk_Final( this )

    class(timeint_rk), intent(inout) :: this
    !----------------------------------------
    
    deallocate( this%coef_a, this%coef_b, this%coef_c )
    select case(this%ndim)
    case(1)
      deallocate( this%tend_buf1D, this%var0_1d )
      if (.not. this%low_storage_flag) deallocate( this%varTmp_1d )
    case(2)
      deallocate( this%tend_buf2D, this%var0_2d )
      if (.not. this%low_storage_flag) deallocate( this%varTmp_2d )
    case(3)
      deallocate( this%tend_buf3D, this%var0_3d )
      if (.not. this%low_storage_flag) deallocate( this%varTmp_3d )
    end select
    
    return
  end subroutine timeint_rk_Final

  !----------------


  subroutine timeint_rk_advance1D( this, nowstage, q, varID, is, ie )
    class(timeint_rk), intent(inout) :: this
    integer, intent(in) :: nowstage
    real(RP), intent(inout) :: q(:)
    integer, intent(in) :: varID
    integer, intent(in) :: is, ie 

    !----------------------------------------    
 
    if (this%low_storage_flag) then
      call rk_advance_low_storage1D( this, nowstage, q, varID, is, ie )
    else
      call rk_advance_general1D( this, nowstage, q, varID, is, ie  )
    end if

  end subroutine timeint_rk_advance1D

  subroutine timeint_rk_advance2D( this, nowstage, q, varID, is, ie ,js, je )
    class(timeint_rk), intent(inout) :: this
    integer, intent(in) :: nowstage
    real(RP), intent(inout) :: q(:,:)
    integer, intent(in) :: varID
    integer, intent(in) :: is, ie ,js, je 

    !----------------------------------------    
 
    if (this%low_storage_flag) then
      call rk_advance_low_storage2D( this, nowstage, q, varID, is, ie ,js, je )
    else
      call rk_advance_general2D( this, nowstage, q, varID, is, ie ,js, je  )
    end if

  end subroutine timeint_rk_advance2D

  subroutine timeint_rk_advance3D( this, nowstage, q, varID, is, ie ,js, je ,ks, ke )
    class(timeint_rk), intent(inout) :: this
    integer, intent(in) :: nowstage
    real(RP), intent(inout) :: q(:,:,:)
    integer, intent(in) :: varID
    integer, intent(in) :: is, ie ,js, je ,ks, ke 

    !----------------------------------------    
 
    if (this%low_storage_flag) then
      call rk_advance_low_storage3D( this, nowstage, q, varID, is, ie ,js, je ,ks, ke )
    else
      call rk_advance_general3D( this, nowstage, q, varID, is, ie ,js, je ,ks, ke  )
    end if

  end subroutine timeint_rk_advance3D

!-------------------



  subroutine rk_advance_low_storage1D( this, nowstage, q, varID, is, ie  )
    class(timeint_rk), intent(inout) :: this
    integer, intent(in) :: nowstage
    real(RP), intent(inout) :: q(:)
    integer, intent(in) :: varID
    integer, intent(in) :: is, ie 

    integer :: i, j, k
    real(RP) :: a_ss

    !----------------------------------------    

    call PROF_rapstart( 'rk_advance_low_storage', 2)    
    if (nowstage == 1) then
      do i=is, ie
        this%var0_1D(i,varID) = q(i)
      end do
    end if   
    a_ss = this%coef_a(nowstage,nowstage)
    do i=is, ie
      q(i) = (1.0_RP - a_ss)*this%var0_1d(i,varID)                   &
              + a_ss*(q(i) + this%dt * this%tend_buf1D(i,1,varID) )
    end do
    call PROF_rapend( 'rk_advance_low_storage', 2)

  end subroutine rk_advance_low_storage1D


  subroutine rk_advance_low_storage2D( this, nowstage, q, varID, is, ie ,js, je  )
    class(timeint_rk), intent(inout) :: this
    integer, intent(in) :: nowstage
    real(RP), intent(inout) :: q(:,:)
    integer, intent(in) :: varID
    integer, intent(in) :: is, ie ,js, je 

    integer :: i, j, k
    real(RP) :: a_ss

    !----------------------------------------    

    call PROF_rapstart( 'rk_advance_low_storage', 2)    
    if (nowstage == 1) then
      do j=js, je
      do i=is, ie
        this%var0_2D(i,j,varID) = q(i,j)
      end do
      end do
    end if   
    a_ss = this%coef_a(nowstage,nowstage)
    do j=js, je
    do i=is, ie
      q(i,j) = (1.0_RP - a_ss)*this%var0_2d(i,j,varID)                   &
              + a_ss*(q(i,j) + this%dt * this%tend_buf2D(i,j,1,varID) )
    end do
    end do
    call PROF_rapend( 'rk_advance_low_storage', 2)

  end subroutine rk_advance_low_storage2D


  subroutine rk_advance_low_storage3D( this, nowstage, q, varID, is, ie ,js, je ,ks, ke  )
    class(timeint_rk), intent(inout) :: this
    integer, intent(in) :: nowstage
    real(RP), intent(inout) :: q(:,:,:)
    integer, intent(in) :: varID
    integer, intent(in) :: is, ie ,js, je ,ks, ke 

    integer :: i, j, k
    real(RP) :: a_ss

    !----------------------------------------    

    call PROF_rapstart( 'rk_advance_low_storage', 2)    
    if (nowstage == 1) then
      do k=ks, ke
      do j=js, je
      do i=is, ie
        this%var0_3D(i,j,k,varID) = q(i,j,k)
      end do
      end do
      end do
    end if   
    a_ss = this%coef_a(nowstage,nowstage)
    do k=ks, ke
    do j=js, je
    do i=is, ie
      q(i,j,k) = (1.0_RP - a_ss)*this%var0_3d(i,j,k,varID)                   &
              + a_ss*(q(i,j,k) + this%dt * this%tend_buf3D(i,j,k,1,varID) )
    end do
    end do
    end do
    call PROF_rapend( 'rk_advance_low_storage', 2)

  end subroutine rk_advance_low_storage3D


  subroutine rk_advance_general1D( this, nowstage, q, varID, is, ie  )
    class(timeint_rk), intent(inout) :: this
    integer, intent(in) :: nowstage
    real(RP), intent(inout) :: q(:)
    integer, intent(in) :: varID
    integer, intent(in) :: is, ie 

    integer :: i, j, k, s
    real(RP) :: a_ss

    !----------------------------------------    

    if (nowstage == 1) then
      do i=is, ie
        this%var0_1D(i,varID) = q(i)
        this%varTmp_1D(i,varID) = q(i)
      end do
    else if (nowstage == this%nstage ) then
      do i=is, ie
        q(i) =  this%varTmp_1d(i,varID)                                             &
              + this%dt * this%coef_b(nowstage) * this%tend_buf1D(i,1,varID)
      end do
      return
    end if 
    if (this%tend_buf_size == 1) then
      do i=is, ie
        this%varTmp_1d(i,varID) =  this%varTmp_1d(i,varID)                          &
            +  this%dt * this%coef_b(nowstage)*this%tend_buf1d(i,1,varID)
        q(i) = this%var0_1d(i,varID)                                                &
            +  this%dt * this%coef_a(nowstage+1,nowstage)*this%tend_buf1d(i,1,varID)
      end do
    else
      do i=is, ie
        this%varTmp_1d(i,varID) =  this%varTmp_1d(i,varID)                             &
            +  this%dt * this%coef_b(nowstage)*this%tend_buf1d(i,1,varID)
        q(i) = this%var0_1d(i,varID)               
      end do
      do s=1, nowstage
      do i=is, ie
        q(i) = q(i)                                                             &
            +  this%dt * this%coef_a(s,nowstage)*this%tend_buf1d(i,s,varID)
      end do
      end do
    end if

  end subroutine rk_advance_general1D

  subroutine rk_advance_general2D( this, nowstage, q, varID, is, ie ,js, je  )
    class(timeint_rk), intent(inout) :: this
    integer, intent(in) :: nowstage
    real(RP), intent(inout) :: q(:,:)
    integer, intent(in) :: varID
    integer, intent(in) :: is, ie ,js, je 

    integer :: i, j, k, s
    real(RP) :: a_ss

    !----------------------------------------    

    if (nowstage == 1) then
      do j=js, je
      do i=is, ie
        this%var0_2D(i,j,varID) = q(i,j)
        this%varTmp_2D(i,j,varID) = q(i,j)
      end do
      end do
    else if (nowstage == this%nstage ) then
      do j=js, je
      do i=is, ie
        q(i,j) =  this%varTmp_2d(i,j,varID)                                             &
              + this%dt * this%coef_b(nowstage) * this%tend_buf2D(i,j,1,varID)
      end do
      end do
      return
    end if 
    if (this%tend_buf_size == 1) then
      do j=js, je
      do i=is, ie
        this%varTmp_2d(i,j,varID) =  this%varTmp_2d(i,j,varID)                          &
            +  this%dt * this%coef_b(nowstage)*this%tend_buf2d(i,j,1,varID)
        q(i,j) = this%var0_2d(i,j,varID)                                                &
            +  this%dt * this%coef_a(nowstage+1,nowstage)*this%tend_buf2d(i,j,1,varID)
      end do
      end do
    else
      do j=js, je
      do i=is, ie
        this%varTmp_2d(i,j,varID) =  this%varTmp_2d(i,j,varID)                             &
            +  this%dt * this%coef_b(nowstage)*this%tend_buf2d(i,j,1,varID)
        q(i,j) = this%var0_2d(i,j,varID)               
      end do
      end do
      do s=1, nowstage
      do j=js, je
      do i=is, ie
        q(i,j) = q(i,j)                                                             &
            +  this%dt * this%coef_a(s,nowstage)*this%tend_buf2d(i,j,s,varID)
      end do
      end do
      end do
    end if

  end subroutine rk_advance_general2D

  subroutine rk_advance_general3D( this, nowstage, q, varID, is, ie ,js, je ,ks, ke  )
    class(timeint_rk), intent(inout) :: this
    integer, intent(in) :: nowstage
    real(RP), intent(inout) :: q(:,:,:)
    integer, intent(in) :: varID
    integer, intent(in) :: is, ie ,js, je ,ks, ke 

    integer :: i, j, k, s
    real(RP) :: a_ss

    !----------------------------------------    

    if (nowstage == 1) then
      do k=ks, ke
      do j=js, je
      do i=is, ie
        this%var0_3D(i,j,k,varID) = q(i,j,k)
        this%varTmp_3D(i,j,k,varID) = q(i,j,k)
      end do
      end do
      end do
    else if (nowstage == this%nstage ) then
      do k=ks, ke
      do j=js, je
      do i=is, ie
        q(i,j,k) =  this%varTmp_3d(i,j,k,varID)                                             &
              + this%dt * this%coef_b(nowstage) * this%tend_buf3D(i,j,k,1,varID)
      end do
      end do
      end do
      return
    end if 
    if (this%tend_buf_size == 1) then
      do k=ks, ke
      do j=js, je
      do i=is, ie
        this%varTmp_3d(i,j,k,varID) =  this%varTmp_3d(i,j,k,varID)                          &
            +  this%dt * this%coef_b(nowstage)*this%tend_buf3d(i,j,k,1,varID)
        q(i,j,k) = this%var0_3d(i,j,k,varID)                                                &
            +  this%dt * this%coef_a(nowstage+1,nowstage)*this%tend_buf3d(i,j,k,1,varID)
      end do
      end do
      end do
    else
      do k=ks, ke
      do j=js, je
      do i=is, ie
        this%varTmp_3d(i,j,k,varID) =  this%varTmp_3d(i,j,k,varID)                             &
            +  this%dt * this%coef_b(nowstage)*this%tend_buf3d(i,j,k,1,varID)
        q(i,j,k) = this%var0_3d(i,j,k,varID)               
      end do
      end do
      end do
      do s=1, nowstage
      do k=ks, ke
      do j=js, je
      do i=is, ie
        q(i,j,k) = q(i,j,k)                                                             &
            +  this%dt * this%coef_a(s,nowstage)*this%tend_buf3d(i,j,k,s,varID)
      end do
      end do
      end do
      end do
    end if

  end subroutine rk_advance_general3D
end module mod_timeint_rk

