
!-------------------------------------------------------------------------------
! Warning: This file was generated from element/scale_element_operation_tensorprod3D.F90.erb.
!          Do not edit this file.
!-------------------------------------------------------------------------------
!-------------------------------------------------------------------------------
!> module FElib / Element / Operation with 3D tensor product elements
!!
!! @par Description
!!           A module for providing mathematical operations assuming a 3D tensor product element with (p+1)^3 DOF
!!
!! @author Yuta Kawai, Xuanzhengbo Ren, and Team SCALE
!!
!<
#include "scaleFElib.h"
module scale_element_operation_tensorprod3D

  !-----------------------------------------------------------------------------
  !
  !++ used modules
  !
  use scale_precision

  use scale_element_base, only: &
    ElementBase3D, &
    ElementBase3D_Init, ElementBase3D_Final

  use scale_element_operation_base, only: ElementOperationBase3D

  !-----------------------------------------------------------------------------
  implicit none
  private

  !-----------------------------------------------------------------------------
  !
  !++ Public type & procedure
  !  
  type, public, extends(ElementOperationBase3D) :: ElementOperationTensorProd3D_P1
    real(RP) :: Dx1D(2,2)
    real(RP) :: Dy1D(2,2)
    real(RP) :: Dz1D(2,2)
    real(RP) :: Dy1D_tr(2,2)
    real(RP) :: Dz1D_tr(2,2)
  contains
    procedure, public :: Dx => element_operation_tensorprod3D_Dx_P1
    procedure, public :: Dy => element_operation_tensorprod3D_Dy_P1
    procedure, public :: Dz => element_operation_tensorprod3D_Dz_P1
    procedure, public :: Grad => element_operation_tensorprod3D_Grad_P1
  end type ElementOperationTensorProd3D_P1
  type, public, extends(ElementOperationBase3D) :: ElementOperationTensorProd3D_P2
    real(RP) :: Dx1D(3,3)
    real(RP) :: Dy1D(3,3)
    real(RP) :: Dz1D(3,3)
    real(RP) :: Dy1D_tr(3,3)
    real(RP) :: Dz1D_tr(3,3)
  contains
    procedure, public :: Dx => element_operation_tensorprod3D_Dx_P2
    procedure, public :: Dy => element_operation_tensorprod3D_Dy_P2
    procedure, public :: Dz => element_operation_tensorprod3D_Dz_P2
    procedure, public :: Grad => element_operation_tensorprod3D_Grad_P2
  end type ElementOperationTensorProd3D_P2
  type, public, extends(ElementOperationBase3D) :: ElementOperationTensorProd3D_P3
    real(RP) :: Dx1D(4,4)
    real(RP) :: Dy1D(4,4)
    real(RP) :: Dz1D(4,4)
    real(RP) :: Dy1D_tr(4,4)
    real(RP) :: Dz1D_tr(4,4)
  contains
    procedure, public :: Dx => element_operation_tensorprod3D_Dx_P3
    procedure, public :: Dy => element_operation_tensorprod3D_Dy_P3
    procedure, public :: Dz => element_operation_tensorprod3D_Dz_P3
    procedure, public :: Grad => element_operation_tensorprod3D_Grad_P3
  end type ElementOperationTensorProd3D_P3
  type, public, extends(ElementOperationBase3D) :: ElementOperationTensorProd3D_P4
    real(RP) :: Dx1D(5,5)
    real(RP) :: Dy1D(5,5)
    real(RP) :: Dz1D(5,5)
    real(RP) :: Dy1D_tr(5,5)
    real(RP) :: Dz1D_tr(5,5)
  contains
    procedure, public :: Dx => element_operation_tensorprod3D_Dx_P4
    procedure, public :: Dy => element_operation_tensorprod3D_Dy_P4
    procedure, public :: Dz => element_operation_tensorprod3D_Dz_P4
    procedure, public :: Grad => element_operation_tensorprod3D_Grad_P4
  end type ElementOperationTensorProd3D_P4
  type, public, extends(ElementOperationBase3D) :: ElementOperationTensorProd3D_P5
    real(RP) :: Dx1D(6,6)
    real(RP) :: Dy1D(6,6)
    real(RP) :: Dz1D(6,6)
    real(RP) :: Dy1D_tr(6,6)
    real(RP) :: Dz1D_tr(6,6)
  contains
    procedure, public :: Dx => element_operation_tensorprod3D_Dx_P5
    procedure, public :: Dy => element_operation_tensorprod3D_Dy_P5
    procedure, public :: Dz => element_operation_tensorprod3D_Dz_P5
    procedure, public :: Grad => element_operation_tensorprod3D_Grad_P5
  end type ElementOperationTensorProd3D_P5
  type, public, extends(ElementOperationBase3D) :: ElementOperationTensorProd3D_P6
    real(RP) :: Dx1D(7,7)
    real(RP) :: Dy1D(7,7)
    real(RP) :: Dz1D(7,7)
    real(RP) :: Dy1D_tr(7,7)
    real(RP) :: Dz1D_tr(7,7)
  contains
    procedure, public :: Dx => element_operation_tensorprod3D_Dx_P6
    procedure, public :: Dy => element_operation_tensorprod3D_Dy_P6
    procedure, public :: Dz => element_operation_tensorprod3D_Dz_P6
    procedure, public :: Grad => element_operation_tensorprod3D_Grad_P6
  end type ElementOperationTensorProd3D_P6
  type, public, extends(ElementOperationBase3D) :: ElementOperationTensorProd3D_P7
    real(RP) :: Dx1D(8,8)
    real(RP) :: Dy1D(8,8)
    real(RP) :: Dz1D(8,8)
    real(RP) :: Dy1D_tr(8,8)
    real(RP) :: Dz1D_tr(8,8)
  contains
    procedure, public :: Dx => element_operation_tensorprod3D_Dx_P7
    procedure, public :: Dy => element_operation_tensorprod3D_Dy_P7
    procedure, public :: Dz => element_operation_tensorprod3D_Dz_P7
    procedure, public :: Grad => element_operation_tensorprod3D_Grad_P7
  end type ElementOperationTensorProd3D_P7
  type, public, extends(ElementOperationBase3D) :: ElementOperationTensorProd3D_P8
    real(RP) :: Dx1D(9,9)
    real(RP) :: Dy1D(9,9)
    real(RP) :: Dz1D(9,9)
    real(RP) :: Dy1D_tr(9,9)
    real(RP) :: Dz1D_tr(9,9)
  contains
    procedure, public :: Dx => element_operation_tensorprod3D_Dx_P8
    procedure, public :: Dy => element_operation_tensorprod3D_Dy_P8
    procedure, public :: Dz => element_operation_tensorprod3D_Dz_P8
    procedure, public :: Grad => element_operation_tensorprod3D_Grad_P8
  end type ElementOperationTensorProd3D_P8
  type, public, extends(ElementOperationBase3D) :: ElementOperationTensorProd3D_P9
    real(RP) :: Dx1D(10,10)
    real(RP) :: Dy1D(10,10)
    real(RP) :: Dz1D(10,10)
    real(RP) :: Dy1D_tr(10,10)
    real(RP) :: Dz1D_tr(10,10)
  contains
    procedure, public :: Dx => element_operation_tensorprod3D_Dx_P9
    procedure, public :: Dy => element_operation_tensorprod3D_Dy_P9
    procedure, public :: Dz => element_operation_tensorprod3D_Dz_P9
    procedure, public :: Grad => element_operation_tensorprod3D_Grad_P9
  end type ElementOperationTensorProd3D_P9
  type, public, extends(ElementOperationBase3D) :: ElementOperationTensorProd3D_P10
    real(RP) :: Dx1D(11,11)
    real(RP) :: Dy1D(11,11)
    real(RP) :: Dz1D(11,11)
    real(RP) :: Dy1D_tr(11,11)
    real(RP) :: Dz1D_tr(11,11)
  contains
    procedure, public :: Dx => element_operation_tensorprod3D_Dx_P10
    procedure, public :: Dy => element_operation_tensorprod3D_Dy_P10
    procedure, public :: Dz => element_operation_tensorprod3D_Dz_P10
    procedure, public :: Grad => element_operation_tensorprod3D_Grad_P10
  end type ElementOperationTensorProd3D_P10
  type, public, extends(ElementOperationBase3D) :: ElementOperationTensorProd3D_P11
    real(RP) :: Dx1D(12,12)
    real(RP) :: Dy1D(12,12)
    real(RP) :: Dz1D(12,12)
    real(RP) :: Dy1D_tr(12,12)
    real(RP) :: Dz1D_tr(12,12)
  contains
    procedure, public :: Dx => element_operation_tensorprod3D_Dx_P11
    procedure, public :: Dy => element_operation_tensorprod3D_Dy_P11
    procedure, public :: Dz => element_operation_tensorprod3D_Dz_P11
    procedure, public :: Grad => element_operation_tensorprod3D_Grad_P11
  end type ElementOperationTensorProd3D_P11
  type, public, extends(ElementOperationBase3D) :: ElementOperationTensorProd3D_P12
    real(RP) :: Dx1D(13,13)
    real(RP) :: Dy1D(13,13)
    real(RP) :: Dz1D(13,13)
    real(RP) :: Dy1D_tr(13,13)
    real(RP) :: Dz1D_tr(13,13)
  contains
    procedure, public :: Dx => element_operation_tensorprod3D_Dx_P12
    procedure, public :: Dy => element_operation_tensorprod3D_Dy_P12
    procedure, public :: Dz => element_operation_tensorprod3D_Dz_P12
    procedure, public :: Grad => element_operation_tensorprod3D_Grad_P12
  end type ElementOperationTensorProd3D_P12
  type, public, extends(ElementOperationBase3D) :: ElementOperationTensorProd3D_P13
    real(RP) :: Dx1D(14,14)
    real(RP) :: Dy1D(14,14)
    real(RP) :: Dz1D(14,14)
    real(RP) :: Dy1D_tr(14,14)
    real(RP) :: Dz1D_tr(14,14)
  contains
    procedure, public :: Dx => element_operation_tensorprod3D_Dx_P13
    procedure, public :: Dy => element_operation_tensorprod3D_Dy_P13
    procedure, public :: Dz => element_operation_tensorprod3D_Dz_P13
    procedure, public :: Grad => element_operation_tensorprod3D_Grad_P13
  end type ElementOperationTensorProd3D_P13

contains

!> Calculate the differential in x-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dx_P1( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirX_P1
    implicit none
    class(ElementOperationTensorProd3D_P1), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D**2)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D**2)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirX_P1( this%Dx1D, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dx_P1

!> Calculate the differential in x-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dx_P2( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirX_P2
    implicit none
    class(ElementOperationTensorProd3D_P2), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D**2)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D**2)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirX_P2( this%Dx1D, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dx_P2

!> Calculate the differential in x-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dx_P3( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirX_P3
    implicit none
    class(ElementOperationTensorProd3D_P3), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D**2)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D**2)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirX_P3( this%Dx1D, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dx_P3

!> Calculate the differential in x-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dx_P4( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirX_P4
    implicit none
    class(ElementOperationTensorProd3D_P4), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D**2)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D**2)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirX_P4( this%Dx1D, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dx_P4

!> Calculate the differential in x-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dx_P5( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirX_P5
    implicit none
    class(ElementOperationTensorProd3D_P5), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D**2)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D**2)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirX_P5( this%Dx1D, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dx_P5

!> Calculate the differential in x-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dx_P6( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirX_P6
    implicit none
    class(ElementOperationTensorProd3D_P6), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D**2)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D**2)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirX_P6( this%Dx1D, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dx_P6

!> Calculate the differential in x-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dx_P7( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirX_P7
    implicit none
    class(ElementOperationTensorProd3D_P7), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D**2)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D**2)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirX_P7( this%Dx1D, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dx_P7

!> Calculate the differential in x-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dx_P8( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirX_P8
    implicit none
    class(ElementOperationTensorProd3D_P8), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D**2)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D**2)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirX_P8( this%Dx1D, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dx_P8

!> Calculate the differential in x-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dx_P9( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirX_P9
    implicit none
    class(ElementOperationTensorProd3D_P9), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D**2)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D**2)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirX_P9( this%Dx1D, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dx_P9

!> Calculate the differential in x-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dx_P10( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirX_P10
    implicit none
    class(ElementOperationTensorProd3D_P10), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D**2)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D**2)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirX_P10( this%Dx1D, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dx_P10

!> Calculate the differential in x-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dx_P11( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirX_P11
    implicit none
    class(ElementOperationTensorProd3D_P11), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D**2)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D**2)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirX_P11( this%Dx1D, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dx_P11

!> Calculate the differential in x-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dx_P12( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirX_P12
    implicit none
    class(ElementOperationTensorProd3D_P12), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D**2)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D**2)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirX_P12( this%Dx1D, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dx_P12

!> Calculate the differential in x-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dx_P13( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirX_P13
    implicit none
    class(ElementOperationTensorProd3D_P13), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D**2)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D**2)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirX_P13( this%Dx1D, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dx_P13

!-------------------------------------------------------------


!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dy_P1( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirY_P1
    implicit none
    class(ElementOperationTensorProd3D_P1), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirY_P1( this%Dy1D_tr, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dy_P1

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dy_P2( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirY_P2
    implicit none
    class(ElementOperationTensorProd3D_P2), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirY_P2( this%Dy1D_tr, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dy_P2

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dy_P3( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirY_P3
    implicit none
    class(ElementOperationTensorProd3D_P3), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirY_P3( this%Dy1D_tr, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dy_P3

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dy_P4( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirY_P4
    implicit none
    class(ElementOperationTensorProd3D_P4), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirY_P4( this%Dy1D_tr, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dy_P4

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dy_P5( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirY_P5
    implicit none
    class(ElementOperationTensorProd3D_P5), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirY_P5( this%Dy1D_tr, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dy_P5

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dy_P6( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirY_P6
    implicit none
    class(ElementOperationTensorProd3D_P6), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirY_P6( this%Dy1D_tr, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dy_P6

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dy_P7( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirY_P7
    implicit none
    class(ElementOperationTensorProd3D_P7), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirY_P7( this%Dy1D_tr, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dy_P7

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dy_P8( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirY_P8
    implicit none
    class(ElementOperationTensorProd3D_P8), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirY_P8( this%Dy1D_tr, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dy_P8

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dy_P9( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirY_P9
    implicit none
    class(ElementOperationTensorProd3D_P9), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirY_P9( this%Dy1D_tr, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dy_P9

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dy_P10( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirY_P10
    implicit none
    class(ElementOperationTensorProd3D_P10), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirY_P10( this%Dy1D_tr, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dy_P10

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dy_P11( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirY_P11
    implicit none
    class(ElementOperationTensorProd3D_P11), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirY_P11( this%Dy1D_tr, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dy_P11

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dy_P12( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirY_P12
    implicit none
    class(ElementOperationTensorProd3D_P12), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirY_P12( this%Dy1D_tr, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dy_P12

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dy_P13( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirY_P13
    implicit none
    class(ElementOperationTensorProd3D_P13), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirY_P13( this%Dy1D_tr, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dy_P13

!-------------------------------------------------------------


!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dz_P1( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirZ_P1
    implicit none
    class(ElementOperationTensorProd3D_P1), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirZ_P1( this%Dz1D_tr, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dz_P1

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dz_P2( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirZ_P2
    implicit none
    class(ElementOperationTensorProd3D_P2), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirZ_P2( this%Dz1D_tr, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dz_P2

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dz_P3( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirZ_P3
    implicit none
    class(ElementOperationTensorProd3D_P3), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirZ_P3( this%Dz1D_tr, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dz_P3

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dz_P4( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirZ_P4
    implicit none
    class(ElementOperationTensorProd3D_P4), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirZ_P4( this%Dz1D_tr, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dz_P4

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dz_P5( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirZ_P5
    implicit none
    class(ElementOperationTensorProd3D_P5), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirZ_P5( this%Dz1D_tr, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dz_P5

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dz_P6( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirZ_P6
    implicit none
    class(ElementOperationTensorProd3D_P6), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirZ_P6( this%Dz1D_tr, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dz_P6

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dz_P7( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirZ_P7
    implicit none
    class(ElementOperationTensorProd3D_P7), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirZ_P7( this%Dz1D_tr, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dz_P7

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dz_P8( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirZ_P8
    implicit none
    class(ElementOperationTensorProd3D_P8), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirZ_P8( this%Dz1D_tr, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dz_P8

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dz_P9( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirZ_P9
    implicit none
    class(ElementOperationTensorProd3D_P9), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirZ_P9( this%Dz1D_tr, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dz_P9

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dz_P10( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirZ_P10
    implicit none
    class(ElementOperationTensorProd3D_P10), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirZ_P10( this%Dz1D_tr, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dz_P10

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dz_P11( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirZ_P11
    implicit none
    class(ElementOperationTensorProd3D_P11), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirZ_P11( this%Dz1D_tr, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dz_P11

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dz_P12( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirZ_P12
    implicit none
    class(ElementOperationTensorProd3D_P12), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirZ_P12( this%Dz1D_tr, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dz_P12

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Dz_P13( this, vec_in, vec_out )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_dirZ_P13
    implicit none
    class(ElementOperationTensorProd3D_P13), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_dirZ_P13( this%Dz1D_tr, vec_in, vec_out )
    return
  end subroutine element_operation_tensorprod3D_Dz_P13

!-------------------------------------------------------------


!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Grad_P1( this, vec_in, vec_out_dx, vec_out_dy, vec_out_dz )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_gradlike_dirXYZ_P1
    implicit none
    class(ElementOperationTensorProd3D_P1), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dx(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dy(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dz(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_gradlike_dirXYZ_P1( this%Dx1D, this%Dy1D_tr, this%Dz1D_tr, vec_in, &
      vec_out_dx, vec_out_dy, vec_out_dz )
    return
  end subroutine element_operation_tensorprod3D_Grad_P1

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Grad_P2( this, vec_in, vec_out_dx, vec_out_dy, vec_out_dz )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_gradlike_dirXYZ_P2
    implicit none
    class(ElementOperationTensorProd3D_P2), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dx(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dy(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dz(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_gradlike_dirXYZ_P2( this%Dx1D, this%Dy1D_tr, this%Dz1D_tr, vec_in, &
      vec_out_dx, vec_out_dy, vec_out_dz )
    return
  end subroutine element_operation_tensorprod3D_Grad_P2

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Grad_P3( this, vec_in, vec_out_dx, vec_out_dy, vec_out_dz )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_gradlike_dirXYZ_P3
    implicit none
    class(ElementOperationTensorProd3D_P3), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dx(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dy(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dz(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_gradlike_dirXYZ_P3( this%Dx1D, this%Dy1D_tr, this%Dz1D_tr, vec_in, &
      vec_out_dx, vec_out_dy, vec_out_dz )
    return
  end subroutine element_operation_tensorprod3D_Grad_P3

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Grad_P4( this, vec_in, vec_out_dx, vec_out_dy, vec_out_dz )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_gradlike_dirXYZ_P4
    implicit none
    class(ElementOperationTensorProd3D_P4), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dx(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dy(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dz(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_gradlike_dirXYZ_P4( this%Dx1D, this%Dy1D_tr, this%Dz1D_tr, vec_in, &
      vec_out_dx, vec_out_dy, vec_out_dz )
    return
  end subroutine element_operation_tensorprod3D_Grad_P4

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Grad_P5( this, vec_in, vec_out_dx, vec_out_dy, vec_out_dz )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_gradlike_dirXYZ_P5
    implicit none
    class(ElementOperationTensorProd3D_P5), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dx(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dy(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dz(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_gradlike_dirXYZ_P5( this%Dx1D, this%Dy1D_tr, this%Dz1D_tr, vec_in, &
      vec_out_dx, vec_out_dy, vec_out_dz )
    return
  end subroutine element_operation_tensorprod3D_Grad_P5

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Grad_P6( this, vec_in, vec_out_dx, vec_out_dy, vec_out_dz )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_gradlike_dirXYZ_P6
    implicit none
    class(ElementOperationTensorProd3D_P6), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dx(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dy(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dz(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_gradlike_dirXYZ_P6( this%Dx1D, this%Dy1D_tr, this%Dz1D_tr, vec_in, &
      vec_out_dx, vec_out_dy, vec_out_dz )
    return
  end subroutine element_operation_tensorprod3D_Grad_P6

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Grad_P7( this, vec_in, vec_out_dx, vec_out_dy, vec_out_dz )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_gradlike_dirXYZ_P7
    implicit none
    class(ElementOperationTensorProd3D_P7), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dx(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dy(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dz(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_gradlike_dirXYZ_P7( this%Dx1D, this%Dy1D_tr, this%Dz1D_tr, vec_in, &
      vec_out_dx, vec_out_dy, vec_out_dz )
    return
  end subroutine element_operation_tensorprod3D_Grad_P7

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Grad_P8( this, vec_in, vec_out_dx, vec_out_dy, vec_out_dz )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_gradlike_dirXYZ_P8
    implicit none
    class(ElementOperationTensorProd3D_P8), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dx(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dy(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dz(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_gradlike_dirXYZ_P8( this%Dx1D, this%Dy1D_tr, this%Dz1D_tr, vec_in, &
      vec_out_dx, vec_out_dy, vec_out_dz )
    return
  end subroutine element_operation_tensorprod3D_Grad_P8

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Grad_P9( this, vec_in, vec_out_dx, vec_out_dy, vec_out_dz )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_gradlike_dirXYZ_P9
    implicit none
    class(ElementOperationTensorProd3D_P9), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dx(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dy(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dz(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_gradlike_dirXYZ_P9( this%Dx1D, this%Dy1D_tr, this%Dz1D_tr, vec_in, &
      vec_out_dx, vec_out_dy, vec_out_dz )
    return
  end subroutine element_operation_tensorprod3D_Grad_P9

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Grad_P10( this, vec_in, vec_out_dx, vec_out_dy, vec_out_dz )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_gradlike_dirXYZ_P10
    implicit none
    class(ElementOperationTensorProd3D_P10), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dx(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dy(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dz(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_gradlike_dirXYZ_P10( this%Dx1D, this%Dy1D_tr, this%Dz1D_tr, vec_in, &
      vec_out_dx, vec_out_dy, vec_out_dz )
    return
  end subroutine element_operation_tensorprod3D_Grad_P10

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Grad_P11( this, vec_in, vec_out_dx, vec_out_dy, vec_out_dz )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_gradlike_dirXYZ_P11
    implicit none
    class(ElementOperationTensorProd3D_P11), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dx(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dy(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dz(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_gradlike_dirXYZ_P11( this%Dx1D, this%Dy1D_tr, this%Dz1D_tr, vec_in, &
      vec_out_dx, vec_out_dy, vec_out_dz )
    return
  end subroutine element_operation_tensorprod3D_Grad_P11

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Grad_P12( this, vec_in, vec_out_dx, vec_out_dy, vec_out_dz )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_gradlike_dirXYZ_P12
    implicit none
    class(ElementOperationTensorProd3D_P12), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dx(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dy(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dz(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_gradlike_dirXYZ_P12( this%Dx1D, this%Dy1D_tr, this%Dz1D_tr, vec_in, &
      vec_out_dx, vec_out_dy, vec_out_dz )
    return
  end subroutine element_operation_tensorprod3D_Grad_P12

!> Calculate the differential in z-direction
!!
!OCL SERIAL
  subroutine element_operation_tensorprod3D_Grad_P13( this, vec_in, vec_out_dx, vec_out_dy, vec_out_dz )
    use scale_element_operation_tensorprod3D_kernel, only: element_operation_tensorprod3D_kernel_matrix_vec_gradlike_dirXYZ_P13
    implicit none
    class(ElementOperationTensorProd3D_P13), intent(in) :: this
    real(RP), intent(in) :: vec_in(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dx(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dy(this%Np1D,this%Np1D,this%Np1D)
    real(RP), intent(out) :: vec_out_dz(this%Np1D,this%Np1D,this%Np1D)
    !----------------------------------------------------------
    call element_tensorprod3D_operation_kernel_matrix_vec_gradlike_dirXYZ_P13( this%Dx1D, this%Dy1D_tr, this%Dz1D_tr, vec_in, &
      vec_out_dx, vec_out_dy, vec_out_dz )
    return
  end subroutine element_operation_tensorprod3D_Grad_P13

end module scale_element_operation_tensorprod3D