
!-------------------------------------------------------------------------------
! Warning: This file was generated from element/scale_element_operation_gpu_driver.F90.erb.
!          Do not edit this file.
!-------------------------------------------------------------------------------
!-------------------------------------------------------------------------------
!> module FElib / Element / Driver for operation with 3D tensor product elements using GPU
!!
!! @par Description
!!           A driver module for providing kernels of matrix and vector operations assuming a 3D tensor product element with (p+1)^3 DOF and GPU execution. 
!!
!! @author Yuta Kawai, Xuanzhengbo Ren, and Team SCALE
!!
!<
#include "scaleFElib.h"
module scale_element_operation_gpu_driver

  !-----------------------------------------------------------------------------
  !
  !++ used modules
  !
  use scale_precision
  use scale_io

  use scale_element_base, only: ElementBase3D
  use scale_element_operation_base, only: ElementOperationBase3D
  use scale_element_operation_tensorprod3D
  use scale_element_operation_tensorprod3D_kernel_gpu

  !-----------------------------------------------------------------------------
  implicit none
  private

  !-----------------------------------------------------------------------------
  !
  !++ Public type & procedure
  !  
  !> Driver for element operation with 3D tensor product elements using GPU
  type, public :: ElementOperationGPUDriver
    type(ElementOperationTensorProd3D_P1), pointer :: elem_optr_tensorprod3D_P1
    type(ElementOperationTensorProd3D_P2), pointer :: elem_optr_tensorprod3D_P2
    type(ElementOperationTensorProd3D_P3), pointer :: elem_optr_tensorprod3D_P3
    type(ElementOperationTensorProd3D_P4), pointer :: elem_optr_tensorprod3D_P4
    type(ElementOperationTensorProd3D_P5), pointer :: elem_optr_tensorprod3D_P5
    type(ElementOperationTensorProd3D_P6), pointer :: elem_optr_tensorprod3D_P6
    type(ElementOperationTensorProd3D_P7), pointer :: elem_optr_tensorprod3D_P7
    type(ElementOperationTensorProd3D_P8), pointer :: elem_optr_tensorprod3D_P8
    type(ElementOperationTensorProd3D_P9), pointer :: elem_optr_tensorprod3D_P9
    type(ElementOperationTensorProd3D_P10), pointer :: elem_optr_tensorprod3D_P10
    type(ElementOperationTensorProd3D_P11), pointer :: elem_optr_tensorprod3D_P11
    type(ElementOperationTensorProd3D_P12), pointer :: elem_optr_tensorprod3D_P12
    type(ElementOperationTensorProd3D_P13), pointer :: elem_optr_tensorprod3D_P13
    type(ElementOperationTensorProd3D_P14), pointer :: elem_optr_tensorprod3D_P14
    type(ElementOperationTensorProd3D_P15), pointer :: elem_optr_tensorprod3D_P15
    integer :: nnode_h1D
    integer :: Nnode_v
    integer :: NfpTot
  contains
    procedure :: Init => ElementOperationGPU_Init
    procedure :: Final => ElementOperationGPU_Final
  end type ElementOperationGPUDriver

  public :: ElementOperationGPU_Div_kplane
  public :: ElementOperationGPU_DivVar5_kplane
  public :: ElementOperationGPU_DivVar5_kplane2
  public :: ElementOperationGPU_DivVar5_z_lift
  public :: ElementOperationGPU_DivVar5  
  public :: ElementOperationGPU_VFilterPM1
  public :: ElementOperationGPU_ModalFilter_var5

contains
  !> Initialize an object of ElementOperationGPUDriver 
  !!
  !! The pointer to the given ElementOperationBase3D object are attached and necessary data is transferred to GPU.
  subroutine ElementOperationGPU_Init( this, elem_optr_base3D )
    use scale_prc, only: PRC_abort
    implicit none
    class(ElementOperationGPUDriver), intent(inout) :: this               !< An object of ElementOperationGPUDriver to be initialized
    class(ElementOperationBase3D), intent(in), target :: elem_optr_base3D !< An obect of 3D element operation base tyoe 
    !----------------------------------------------------------

    !$acc enter data create(this)

    this%Nnode_h1D = elem_optr_base3D%elem3D%Nnode_h1D
    this%Nnode_v = elem_optr_base3D%elem3D%Nnode_v
    this%NfpTot = elem_optr_base3D%elem3D%NfpTot
    !$acc update device(this%Nnode_h1D, this%Nnode_v, this%NfpTot)

    select type(elem_optr_base3D)
    type is (ElementOperationTensorProd3D_P1)
        this%elem_optr_tensorprod3D_P1 => elem_optr_base3D
        !$acc enter data attach(this%elem_optr_tensorprod3D_P1)
    type is (ElementOperationTensorProd3D_P2)
        this%elem_optr_tensorprod3D_P2 => elem_optr_base3D
        !$acc enter data attach(this%elem_optr_tensorprod3D_P2)
    type is (ElementOperationTensorProd3D_P3)
        this%elem_optr_tensorprod3D_P3 => elem_optr_base3D
        !$acc enter data attach(this%elem_optr_tensorprod3D_P3)
    type is (ElementOperationTensorProd3D_P4)
        this%elem_optr_tensorprod3D_P4 => elem_optr_base3D
        !$acc enter data attach(this%elem_optr_tensorprod3D_P4)
    type is (ElementOperationTensorProd3D_P5)
        this%elem_optr_tensorprod3D_P5 => elem_optr_base3D
        !$acc enter data attach(this%elem_optr_tensorprod3D_P5)
    type is (ElementOperationTensorProd3D_P6)
        this%elem_optr_tensorprod3D_P6 => elem_optr_base3D
        !$acc enter data attach(this%elem_optr_tensorprod3D_P6)
    type is (ElementOperationTensorProd3D_P7)
        this%elem_optr_tensorprod3D_P7 => elem_optr_base3D
        !$acc enter data attach(this%elem_optr_tensorprod3D_P7)
    type is (ElementOperationTensorProd3D_P8)
        this%elem_optr_tensorprod3D_P8 => elem_optr_base3D
        !$acc enter data attach(this%elem_optr_tensorprod3D_P8)
    type is (ElementOperationTensorProd3D_P9)
        this%elem_optr_tensorprod3D_P9 => elem_optr_base3D
        !$acc enter data attach(this%elem_optr_tensorprod3D_P9)
    type is (ElementOperationTensorProd3D_P10)
        this%elem_optr_tensorprod3D_P10 => elem_optr_base3D
        !$acc enter data attach(this%elem_optr_tensorprod3D_P10)
    type is (ElementOperationTensorProd3D_P11)
        this%elem_optr_tensorprod3D_P11 => elem_optr_base3D
        !$acc enter data attach(this%elem_optr_tensorprod3D_P11)
    type is (ElementOperationTensorProd3D_P12)
        this%elem_optr_tensorprod3D_P12 => elem_optr_base3D
        !$acc enter data attach(this%elem_optr_tensorprod3D_P12)
    type is (ElementOperationTensorProd3D_P13)
        this%elem_optr_tensorprod3D_P13 => elem_optr_base3D
        !$acc enter data attach(this%elem_optr_tensorprod3D_P13)
    type is (ElementOperationTensorProd3D_P14)
        this%elem_optr_tensorprod3D_P14 => elem_optr_base3D
        !$acc enter data attach(this%elem_optr_tensorprod3D_P14)
    type is (ElementOperationTensorProd3D_P15)
        this%elem_optr_tensorprod3D_P15 => elem_optr_base3D
        !$acc enter data attach(this%elem_optr_tensorprod3D_P15)
    class default
      LOG_INFO("ElementOperationGPU_Init",*) "Unsupported type is specified for elem_optr_base3D. Check!"
      call PRC_abort
    end select
    
    return
  end subroutine ElementOperationGPU_Init

  !> Finalize an object of ElementOperationGPUDriver
  subroutine ElementOperationGPU_Final( this )
    implicit none
    class(ElementOperationGPUDriver), intent(inout) :: this
    !----------------------------------------------------------
    !$acc exit data delete(this)
    return
  end subroutine ElementOperationGPU_Final

  subroutine ElementOperationGPU_VFilterPM1( this, vec_in, Ne_in, Ne_out, vec_out )
    implicit none
    type(ElementOperationGPUDriver), intent(in) :: this
    integer, intent(in) :: Ne_in, Ne_out
    real(RP), intent(in) :: vec_in(this%Nnode_h1D,this%Nnode_h1D,this%Nnode_v,Ne_in)
    real(RP), intent(out) :: vec_out(this%Nnode_h1D,this%Nnode_h1D,this%Nnode_v,Ne_out)
    !----------------------------------------------------------

    !!$acc routine gang

    select case (this%Nnode_h1D)
    case (2)
        call element_operation_kernel_matvec_dirZ_P1( this%elem_optr_tensorprod3D_P1%IntrpMat_VPOrdM1_tr, vec_in, Ne_in, Ne_out, vec_out )
    case (3)
        call element_operation_kernel_matvec_dirZ_P2( this%elem_optr_tensorprod3D_P2%IntrpMat_VPOrdM1_tr, vec_in, Ne_in, Ne_out, vec_out )
    case (4)
        call element_operation_kernel_matvec_dirZ_P3( this%elem_optr_tensorprod3D_P3%IntrpMat_VPOrdM1_tr, vec_in, Ne_in, Ne_out, vec_out )
    case (5)
        call element_operation_kernel_matvec_dirZ_P4( this%elem_optr_tensorprod3D_P4%IntrpMat_VPOrdM1_tr, vec_in, Ne_in, Ne_out, vec_out )
    case (6)
        call element_operation_kernel_matvec_dirZ_P5( this%elem_optr_tensorprod3D_P5%IntrpMat_VPOrdM1_tr, vec_in, Ne_in, Ne_out, vec_out )
    case (7)
        call element_operation_kernel_matvec_dirZ_P6( this%elem_optr_tensorprod3D_P6%IntrpMat_VPOrdM1_tr, vec_in, Ne_in, Ne_out, vec_out )
    case (8)
        call element_operation_kernel_matvec_dirZ_P7( this%elem_optr_tensorprod3D_P7%IntrpMat_VPOrdM1_tr, vec_in, Ne_in, Ne_out, vec_out )
    case (9)
        call element_operation_kernel_matvec_dirZ_P8( this%elem_optr_tensorprod3D_P8%IntrpMat_VPOrdM1_tr, vec_in, Ne_in, Ne_out, vec_out )
    case (10)
        call element_operation_kernel_matvec_dirZ_P9( this%elem_optr_tensorprod3D_P9%IntrpMat_VPOrdM1_tr, vec_in, Ne_in, Ne_out, vec_out )
    case (11)
        call element_operation_kernel_matvec_dirZ_P10( this%elem_optr_tensorprod3D_P10%IntrpMat_VPOrdM1_tr, vec_in, Ne_in, Ne_out, vec_out )
    case (12)
        call element_operation_kernel_matvec_dirZ_P11( this%elem_optr_tensorprod3D_P11%IntrpMat_VPOrdM1_tr, vec_in, Ne_in, Ne_out, vec_out )
    case (13)
        call element_operation_kernel_matvec_dirZ_P12( this%elem_optr_tensorprod3D_P12%IntrpMat_VPOrdM1_tr, vec_in, Ne_in, Ne_out, vec_out )
    case (14)
        call element_operation_kernel_matvec_dirZ_P13( this%elem_optr_tensorprod3D_P13%IntrpMat_VPOrdM1_tr, vec_in, Ne_in, Ne_out, vec_out )
    case (15)
        call element_operation_kernel_matvec_dirZ_P14( this%elem_optr_tensorprod3D_P14%IntrpMat_VPOrdM1_tr, vec_in, Ne_in, Ne_out, vec_out )
    case (16)
        call element_operation_kernel_matvec_dirZ_P15( this%elem_optr_tensorprod3D_P15%IntrpMat_VPOrdM1_tr, vec_in, Ne_in, Ne_out, vec_out )
    end select
    return
  end subroutine ElementOperationGPU_VFilterPM1

  subroutine ElementOperationGPU_Div_kplane( this, Flux2D_kplane, E11, E22, k, div_xy )
    implicit none
    type(ElementOperationGPUDriver), intent(in) :: this
    real(RP), intent(in) :: Flux2D_kplane(this%Nnode_h1D,this%Nnode_h1D,2)
    real(RP), intent(in) :: E11(this%Nnode_h1D,this%Nnode_h1D,this%Nnode_v)
    real(RP), intent(in) :: E22(this%Nnode_h1D,this%Nnode_h1D,this%Nnode_v)
    integer, intent(in) :: k
    real(RP), intent(out) :: div_xy(this%Nnode_h1D,this%Nnode_h1D)
    !----------------------------------------------------------

    !$acc routine vector

    select case (this%Nnode_h1D)
    case (2)
        call element_operation_kernel_matvec_divlike_dirXY_P1( this%elem_optr_tensorprod3D_P1%D1D, this%elem_optr_tensorprod3D_P1%D1D_tr, Flux2D_kplane(:,:,1), Flux2D_kplane(:,:,2),  &
          E11(:,:,k), E22(:,:,k), &
          div_xy )
    case (3)
        call element_operation_kernel_matvec_divlike_dirXY_P2( this%elem_optr_tensorprod3D_P2%D1D, this%elem_optr_tensorprod3D_P2%D1D_tr, Flux2D_kplane(:,:,1), Flux2D_kplane(:,:,2),  &
          E11(:,:,k), E22(:,:,k), &
          div_xy )
    case (4)
        call element_operation_kernel_matvec_divlike_dirXY_P3( this%elem_optr_tensorprod3D_P3%D1D, this%elem_optr_tensorprod3D_P3%D1D_tr, Flux2D_kplane(:,:,1), Flux2D_kplane(:,:,2),  &
          E11(:,:,k), E22(:,:,k), &
          div_xy )
    case (5)
        call element_operation_kernel_matvec_divlike_dirXY_P4( this%elem_optr_tensorprod3D_P4%D1D, this%elem_optr_tensorprod3D_P4%D1D_tr, Flux2D_kplane(:,:,1), Flux2D_kplane(:,:,2),  &
          E11(:,:,k), E22(:,:,k), &
          div_xy )
    case (6)
        call element_operation_kernel_matvec_divlike_dirXY_P5( this%elem_optr_tensorprod3D_P5%D1D, this%elem_optr_tensorprod3D_P5%D1D_tr, Flux2D_kplane(:,:,1), Flux2D_kplane(:,:,2),  &
          E11(:,:,k), E22(:,:,k), &
          div_xy )
    case (7)
        call element_operation_kernel_matvec_divlike_dirXY_P6( this%elem_optr_tensorprod3D_P6%D1D, this%elem_optr_tensorprod3D_P6%D1D_tr, Flux2D_kplane(:,:,1), Flux2D_kplane(:,:,2),  &
          E11(:,:,k), E22(:,:,k), &
          div_xy )
    case (8)
        call element_operation_kernel_matvec_divlike_dirXY_P7( this%elem_optr_tensorprod3D_P7%D1D, this%elem_optr_tensorprod3D_P7%D1D_tr, Flux2D_kplane(:,:,1), Flux2D_kplane(:,:,2),  &
          E11(:,:,k), E22(:,:,k), &
          div_xy )
    case (9)
        call element_operation_kernel_matvec_divlike_dirXY_P8( this%elem_optr_tensorprod3D_P8%D1D, this%elem_optr_tensorprod3D_P8%D1D_tr, Flux2D_kplane(:,:,1), Flux2D_kplane(:,:,2),  &
          E11(:,:,k), E22(:,:,k), &
          div_xy )
    case (10)
        call element_operation_kernel_matvec_divlike_dirXY_P9( this%elem_optr_tensorprod3D_P9%D1D, this%elem_optr_tensorprod3D_P9%D1D_tr, Flux2D_kplane(:,:,1), Flux2D_kplane(:,:,2),  &
          E11(:,:,k), E22(:,:,k), &
          div_xy )
    case (11)
        call element_operation_kernel_matvec_divlike_dirXY_P10( this%elem_optr_tensorprod3D_P10%D1D, this%elem_optr_tensorprod3D_P10%D1D_tr, Flux2D_kplane(:,:,1), Flux2D_kplane(:,:,2),  &
          E11(:,:,k), E22(:,:,k), &
          div_xy )
    case (12)
        call element_operation_kernel_matvec_divlike_dirXY_P11( this%elem_optr_tensorprod3D_P11%D1D, this%elem_optr_tensorprod3D_P11%D1D_tr, Flux2D_kplane(:,:,1), Flux2D_kplane(:,:,2),  &
          E11(:,:,k), E22(:,:,k), &
          div_xy )
    case (13)
        call element_operation_kernel_matvec_divlike_dirXY_P12( this%elem_optr_tensorprod3D_P12%D1D, this%elem_optr_tensorprod3D_P12%D1D_tr, Flux2D_kplane(:,:,1), Flux2D_kplane(:,:,2),  &
          E11(:,:,k), E22(:,:,k), &
          div_xy )
    case (14)
        call element_operation_kernel_matvec_divlike_dirXY_P13( this%elem_optr_tensorprod3D_P13%D1D, this%elem_optr_tensorprod3D_P13%D1D_tr, Flux2D_kplane(:,:,1), Flux2D_kplane(:,:,2),  &
          E11(:,:,k), E22(:,:,k), &
          div_xy )
    case (15)
        call element_operation_kernel_matvec_divlike_dirXY_P14( this%elem_optr_tensorprod3D_P14%D1D, this%elem_optr_tensorprod3D_P14%D1D_tr, Flux2D_kplane(:,:,1), Flux2D_kplane(:,:,2),  &
          E11(:,:,k), E22(:,:,k), &
          div_xy )
    case (16)
        call element_operation_kernel_matvec_divlike_dirXY_P15( this%elem_optr_tensorprod3D_P15%D1D, this%elem_optr_tensorprod3D_P15%D1D_tr, Flux2D_kplane(:,:,1), Flux2D_kplane(:,:,2),  &
          E11(:,:,k), E22(:,:,k), &
          div_xy )
    end select
    return
  end subroutine ElementOperationGPU_Div_kplane

    subroutine ElementOperationGPU_DivVar5_kplane( this, Flux2D_kplane, E11, E22, k, div_xy )
    implicit none
    type(ElementOperationGPUDriver), intent(in) :: this
    real(RP), intent(in) :: Flux2D_kplane(this%Nnode_h1D,this%Nnode_h1D,5,2)
    real(RP), intent(in) :: E11(this%Nnode_h1D,this%Nnode_h1D,this%Nnode_v)
    real(RP), intent(in) :: E22(this%Nnode_h1D,this%Nnode_h1D,this%Nnode_v)
    integer, intent(in) :: k
    real(RP), intent(out) :: div_xy(this%Nnode_h1D,this%Nnode_h1D,5)
    !----------------------------------------------------------

    !$acc routine vector

    select case (this%Nnode_h1D)
    case (2)
        call element_operation_kernel_matvec_divlike_dirXY_var5_P1( this%elem_optr_tensorprod3D_P1%D1D, this%elem_optr_tensorprod3D_P1%D1D_tr, Flux2D_kplane(:,:,:,1), Flux2D_kplane(:,:,:,2),  &
          E11(:,:,k), E22(:,:,k), &
          div_xy )
    case (3)
        call element_operation_kernel_matvec_divlike_dirXY_var5_P2( this%elem_optr_tensorprod3D_P2%D1D, this%elem_optr_tensorprod3D_P2%D1D_tr, Flux2D_kplane(:,:,:,1), Flux2D_kplane(:,:,:,2),  &
          E11(:,:,k), E22(:,:,k), &
          div_xy )
    case (4)
        call element_operation_kernel_matvec_divlike_dirXY_var5_P3( this%elem_optr_tensorprod3D_P3%D1D, this%elem_optr_tensorprod3D_P3%D1D_tr, Flux2D_kplane(:,:,:,1), Flux2D_kplane(:,:,:,2),  &
          E11(:,:,k), E22(:,:,k), &
          div_xy )
    case (5)
        call element_operation_kernel_matvec_divlike_dirXY_var5_P4( this%elem_optr_tensorprod3D_P4%D1D, this%elem_optr_tensorprod3D_P4%D1D_tr, Flux2D_kplane(:,:,:,1), Flux2D_kplane(:,:,:,2),  &
          E11(:,:,k), E22(:,:,k), &
          div_xy )
    case (6)
        call element_operation_kernel_matvec_divlike_dirXY_var5_P5( this%elem_optr_tensorprod3D_P5%D1D, this%elem_optr_tensorprod3D_P5%D1D_tr, Flux2D_kplane(:,:,:,1), Flux2D_kplane(:,:,:,2),  &
          E11(:,:,k), E22(:,:,k), &
          div_xy )
    case (7)
        call element_operation_kernel_matvec_divlike_dirXY_var5_P6( this%elem_optr_tensorprod3D_P6%D1D, this%elem_optr_tensorprod3D_P6%D1D_tr, Flux2D_kplane(:,:,:,1), Flux2D_kplane(:,:,:,2),  &
          E11(:,:,k), E22(:,:,k), &
          div_xy )
    case (8)
        call element_operation_kernel_matvec_divlike_dirXY_var5_P7( this%elem_optr_tensorprod3D_P7%D1D, this%elem_optr_tensorprod3D_P7%D1D_tr, Flux2D_kplane(:,:,:,1), Flux2D_kplane(:,:,:,2),  &
          E11(:,:,k), E22(:,:,k), &
          div_xy )
    case (9)
        call element_operation_kernel_matvec_divlike_dirXY_var5_P8( this%elem_optr_tensorprod3D_P8%D1D, this%elem_optr_tensorprod3D_P8%D1D_tr, Flux2D_kplane(:,:,:,1), Flux2D_kplane(:,:,:,2),  &
          E11(:,:,k), E22(:,:,k), &
          div_xy )
    case (10)
        call element_operation_kernel_matvec_divlike_dirXY_var5_P9( this%elem_optr_tensorprod3D_P9%D1D, this%elem_optr_tensorprod3D_P9%D1D_tr, Flux2D_kplane(:,:,:,1), Flux2D_kplane(:,:,:,2),  &
          E11(:,:,k), E22(:,:,k), &
          div_xy )
    case (11)
        call element_operation_kernel_matvec_divlike_dirXY_var5_P10( this%elem_optr_tensorprod3D_P10%D1D, this%elem_optr_tensorprod3D_P10%D1D_tr, Flux2D_kplane(:,:,:,1), Flux2D_kplane(:,:,:,2),  &
          E11(:,:,k), E22(:,:,k), &
          div_xy )
    case (12)
        call element_operation_kernel_matvec_divlike_dirXY_var5_P11( this%elem_optr_tensorprod3D_P11%D1D, this%elem_optr_tensorprod3D_P11%D1D_tr, Flux2D_kplane(:,:,:,1), Flux2D_kplane(:,:,:,2),  &
          E11(:,:,k), E22(:,:,k), &
          div_xy )
    case (13)
        call element_operation_kernel_matvec_divlike_dirXY_var5_P12( this%elem_optr_tensorprod3D_P12%D1D, this%elem_optr_tensorprod3D_P12%D1D_tr, Flux2D_kplane(:,:,:,1), Flux2D_kplane(:,:,:,2),  &
          E11(:,:,k), E22(:,:,k), &
          div_xy )
    case (14)
        call element_operation_kernel_matvec_divlike_dirXY_var5_P13( this%elem_optr_tensorprod3D_P13%D1D, this%elem_optr_tensorprod3D_P13%D1D_tr, Flux2D_kplane(:,:,:,1), Flux2D_kplane(:,:,:,2),  &
          E11(:,:,k), E22(:,:,k), &
          div_xy )
    case (15)
        call element_operation_kernel_matvec_divlike_dirXY_var5_P14( this%elem_optr_tensorprod3D_P14%D1D, this%elem_optr_tensorprod3D_P14%D1D_tr, Flux2D_kplane(:,:,:,1), Flux2D_kplane(:,:,:,2),  &
          E11(:,:,k), E22(:,:,k), &
          div_xy )
    case (16)
        call element_operation_kernel_matvec_divlike_dirXY_var5_P15( this%elem_optr_tensorprod3D_P15%D1D, this%elem_optr_tensorprod3D_P15%D1D_tr, Flux2D_kplane(:,:,:,1), Flux2D_kplane(:,:,:,2),  &
          E11(:,:,k), E22(:,:,k), &
          div_xy )
    end select
    return
  end subroutine ElementOperationGPU_DivVar5_kplane

  subroutine ElementOperationGPU_DivVar5_kplane2( this, Flux2D_kplane_x, Flux2D_kplane_y, E11, E22, k, div_xy )
    implicit none
    type(ElementOperationGPUDriver), intent(in) :: this
    real(RP), intent(in) :: Flux2D_kplane_x(this%Nnode_h1D,this%Nnode_h1D,5)
    real(RP), intent(in) :: Flux2D_kplane_y(this%Nnode_h1D,this%Nnode_h1D,5)
    real(RP), intent(in) :: E11(this%Nnode_h1D,this%Nnode_h1D)
    real(RP), intent(in) :: E22(this%Nnode_h1D,this%Nnode_h1D)
    integer, intent(in) :: k
    real(RP), intent(out) :: div_xy(this%Nnode_h1D,this%Nnode_h1D,5)
    !----------------------------------------------------------

    !$acc routine vector

    select case (this%Nnode_h1D)
    case (2)
        call element_operation_kernel_matvec_divlike_dirXY_var5_P1( this%elem_optr_tensorprod3D_P1%D1D, this%elem_optr_tensorprod3D_P1%D1D_tr, Flux2D_kplane_x, Flux2D_kplane_y,  &
          E11, E22, &
          div_xy )
    case (3)
        call element_operation_kernel_matvec_divlike_dirXY_var5_P2( this%elem_optr_tensorprod3D_P2%D1D, this%elem_optr_tensorprod3D_P2%D1D_tr, Flux2D_kplane_x, Flux2D_kplane_y,  &
          E11, E22, &
          div_xy )
    case (4)
        call element_operation_kernel_matvec_divlike_dirXY_var5_P3( this%elem_optr_tensorprod3D_P3%D1D, this%elem_optr_tensorprod3D_P3%D1D_tr, Flux2D_kplane_x, Flux2D_kplane_y,  &
          E11, E22, &
          div_xy )
    case (5)
        call element_operation_kernel_matvec_divlike_dirXY_var5_P4( this%elem_optr_tensorprod3D_P4%D1D, this%elem_optr_tensorprod3D_P4%D1D_tr, Flux2D_kplane_x, Flux2D_kplane_y,  &
          E11, E22, &
          div_xy )
    case (6)
        call element_operation_kernel_matvec_divlike_dirXY_var5_P5( this%elem_optr_tensorprod3D_P5%D1D, this%elem_optr_tensorprod3D_P5%D1D_tr, Flux2D_kplane_x, Flux2D_kplane_y,  &
          E11, E22, &
          div_xy )
    case (7)
        call element_operation_kernel_matvec_divlike_dirXY_var5_P6( this%elem_optr_tensorprod3D_P6%D1D, this%elem_optr_tensorprod3D_P6%D1D_tr, Flux2D_kplane_x, Flux2D_kplane_y,  &
          E11, E22, &
          div_xy )
    case (8)
        call element_operation_kernel_matvec_divlike_dirXY_var5_P7( this%elem_optr_tensorprod3D_P7%D1D, this%elem_optr_tensorprod3D_P7%D1D_tr, Flux2D_kplane_x, Flux2D_kplane_y,  &
          E11, E22, &
          div_xy )
    case (9)
        call element_operation_kernel_matvec_divlike_dirXY_var5_P8( this%elem_optr_tensorprod3D_P8%D1D, this%elem_optr_tensorprod3D_P8%D1D_tr, Flux2D_kplane_x, Flux2D_kplane_y,  &
          E11, E22, &
          div_xy )
    case (10)
        call element_operation_kernel_matvec_divlike_dirXY_var5_P9( this%elem_optr_tensorprod3D_P9%D1D, this%elem_optr_tensorprod3D_P9%D1D_tr, Flux2D_kplane_x, Flux2D_kplane_y,  &
          E11, E22, &
          div_xy )
    case (11)
        call element_operation_kernel_matvec_divlike_dirXY_var5_P10( this%elem_optr_tensorprod3D_P10%D1D, this%elem_optr_tensorprod3D_P10%D1D_tr, Flux2D_kplane_x, Flux2D_kplane_y,  &
          E11, E22, &
          div_xy )
    case (12)
        call element_operation_kernel_matvec_divlike_dirXY_var5_P11( this%elem_optr_tensorprod3D_P11%D1D, this%elem_optr_tensorprod3D_P11%D1D_tr, Flux2D_kplane_x, Flux2D_kplane_y,  &
          E11, E22, &
          div_xy )
    case (13)
        call element_operation_kernel_matvec_divlike_dirXY_var5_P12( this%elem_optr_tensorprod3D_P12%D1D, this%elem_optr_tensorprod3D_P12%D1D_tr, Flux2D_kplane_x, Flux2D_kplane_y,  &
          E11, E22, &
          div_xy )
    case (14)
        call element_operation_kernel_matvec_divlike_dirXY_var5_P13( this%elem_optr_tensorprod3D_P13%D1D, this%elem_optr_tensorprod3D_P13%D1D_tr, Flux2D_kplane_x, Flux2D_kplane_y,  &
          E11, E22, &
          div_xy )
    case (15)
        call element_operation_kernel_matvec_divlike_dirXY_var5_P14( this%elem_optr_tensorprod3D_P14%D1D, this%elem_optr_tensorprod3D_P14%D1D_tr, Flux2D_kplane_x, Flux2D_kplane_y,  &
          E11, E22, &
          div_xy )
    case (16)
        call element_operation_kernel_matvec_divlike_dirXY_var5_P15( this%elem_optr_tensorprod3D_P15%D1D, this%elem_optr_tensorprod3D_P15%D1D_tr, Flux2D_kplane_x, Flux2D_kplane_y,  &
          E11, E22, &
          div_xy )
    end select
    return
  end subroutine ElementOperationGPU_DivVar5_kplane2

  subroutine ElementOperationGPU_DivVar5_z_lift( this, FluxZ, ebnd_flux, E33, Gsqrt, div3D )
    implicit none
    type(ElementOperationGPUDriver), intent(in) :: this
    real(RP), intent(in) :: FluxZ(this%Nnode_h1D,this%Nnode_h1D,5,this%Nnode_v)
    real(RP), intent(in) :: ebnd_flux(this%NfpTot,5)
    real(RP), intent(in) :: E33(this%Nnode_h1D,this%Nnode_h1D,this%Nnode_v)
    real(RP), intent(in) :: Gsqrt(this%Nnode_h1D,this%Nnode_h1D,this%Nnode_v)
    real(RP), intent(inout) :: div3D(this%Nnode_h1D,this%Nnode_h1D,5,this%Nnode_v)
    !----------------------------------------------------------

    !$acc routine vector
    
    select case (this%Nnode_h1D)
    case (2)
        call element_operation_kernel_matvec_divlike_dirZ_lift_var5_P1( &
          this%elem_optr_tensorprod3D_P1%D1D_tr, this%elem_optr_tensorprod3D_P1%Lift_mat, FluxZ, ebnd_flux, E33, Gsqrt, &
          div3D )
    case (3)
        call element_operation_kernel_matvec_divlike_dirZ_lift_var5_P2( &
          this%elem_optr_tensorprod3D_P2%D1D_tr, this%elem_optr_tensorprod3D_P2%Lift_mat, FluxZ, ebnd_flux, E33, Gsqrt, &
          div3D )
    case (4)
        call element_operation_kernel_matvec_divlike_dirZ_lift_var5_P3( &
          this%elem_optr_tensorprod3D_P3%D1D_tr, this%elem_optr_tensorprod3D_P3%Lift_mat, FluxZ, ebnd_flux, E33, Gsqrt, &
          div3D )
    case (5)
        call element_operation_kernel_matvec_divlike_dirZ_lift_var5_P4( &
          this%elem_optr_tensorprod3D_P4%D1D_tr, this%elem_optr_tensorprod3D_P4%Lift_mat, FluxZ, ebnd_flux, E33, Gsqrt, &
          div3D )
    case (6)
        call element_operation_kernel_matvec_divlike_dirZ_lift_var5_P5( &
          this%elem_optr_tensorprod3D_P5%D1D_tr, this%elem_optr_tensorprod3D_P5%Lift_mat, FluxZ, ebnd_flux, E33, Gsqrt, &
          div3D )
    case (7)
        call element_operation_kernel_matvec_divlike_dirZ_lift_var5_P6( &
          this%elem_optr_tensorprod3D_P6%D1D_tr, this%elem_optr_tensorprod3D_P6%Lift_mat, FluxZ, ebnd_flux, E33, Gsqrt, &
          div3D )
    case (8)
        call element_operation_kernel_matvec_divlike_dirZ_lift_var5_P7( &
          this%elem_optr_tensorprod3D_P7%D1D_tr, this%elem_optr_tensorprod3D_P7%Lift_mat, FluxZ, ebnd_flux, E33, Gsqrt, &
          div3D )
    case (9)
        call element_operation_kernel_matvec_divlike_dirZ_lift_var5_P8( &
          this%elem_optr_tensorprod3D_P8%D1D_tr, this%elem_optr_tensorprod3D_P8%Lift_mat, FluxZ, ebnd_flux, E33, Gsqrt, &
          div3D )
    case (10)
        call element_operation_kernel_matvec_divlike_dirZ_lift_var5_P9( &
          this%elem_optr_tensorprod3D_P9%D1D_tr, this%elem_optr_tensorprod3D_P9%Lift_mat, FluxZ, ebnd_flux, E33, Gsqrt, &
          div3D )
    case (11)
        call element_operation_kernel_matvec_divlike_dirZ_lift_var5_P10( &
          this%elem_optr_tensorprod3D_P10%D1D_tr, this%elem_optr_tensorprod3D_P10%Lift_mat, FluxZ, ebnd_flux, E33, Gsqrt, &
          div3D )
    case (12)
        call element_operation_kernel_matvec_divlike_dirZ_lift_var5_P11( &
          this%elem_optr_tensorprod3D_P11%D1D_tr, this%elem_optr_tensorprod3D_P11%Lift_mat, FluxZ, ebnd_flux, E33, Gsqrt, &
          div3D )
    case (13)
        call element_operation_kernel_matvec_divlike_dirZ_lift_var5_P12( &
          this%elem_optr_tensorprod3D_P12%D1D_tr, this%elem_optr_tensorprod3D_P12%Lift_mat, FluxZ, ebnd_flux, E33, Gsqrt, &
          div3D )
    case (14)
        call element_operation_kernel_matvec_divlike_dirZ_lift_var5_P13( &
          this%elem_optr_tensorprod3D_P13%D1D_tr, this%elem_optr_tensorprod3D_P13%Lift_mat, FluxZ, ebnd_flux, E33, Gsqrt, &
          div3D )
    case (15)
        call element_operation_kernel_matvec_divlike_dirZ_lift_var5_P14( &
          this%elem_optr_tensorprod3D_P14%D1D_tr, this%elem_optr_tensorprod3D_P14%Lift_mat, FluxZ, ebnd_flux, E33, Gsqrt, &
          div3D )
    case (16)
        call element_operation_kernel_matvec_divlike_dirZ_lift_var5_P15( &
          this%elem_optr_tensorprod3D_P15%D1D_tr, this%elem_optr_tensorprod3D_P15%Lift_mat, FluxZ, ebnd_flux, E33, Gsqrt, &
          div3D )
    end select
    return
  end subroutine ElementOperationGPU_DivVar5_z_lift

  subroutine ElementOperationGPU_DivVar5( this, Flux_x, Flux_y, Flux_z, ebnd_flux, E11, E22, E33, Gsqrt, Ne, div3D )
    implicit none
    type(ElementOperationGPUDriver), intent(in) :: this
    integer, intent(in) :: Ne
    real(RP), intent(in) :: Flux_x(this%Nnode_h1D,this%Nnode_h1D,5,this%Nnode_v,Ne)
    real(RP), intent(in) :: Flux_y(this%Nnode_h1D,this%Nnode_h1D,5,this%Nnode_v,Ne)
    real(RP), intent(in) :: Flux_z(this%Nnode_h1D,this%Nnode_h1D,5,this%Nnode_v,Ne)
    real(RP), intent(in) :: ebnd_flux(this%NfpTot,5,Ne)
    real(RP), intent(in) :: E11(this%Nnode_h1D,this%Nnode_h1D,this%Nnode_v,Ne)
    real(RP), intent(in) :: E22(this%Nnode_h1D,this%Nnode_h1D,this%Nnode_v,Ne)
    real(RP), intent(in) :: E33(this%Nnode_h1D,this%Nnode_h1D,this%Nnode_v,Ne)
    real(RP), intent(in) :: Gsqrt(this%Nnode_h1D,this%Nnode_h1D,this%Nnode_v,Ne)
    real(RP), intent(out) :: div3D(this%Nnode_h1D,this%Nnode_h1D,5,this%Nnode_v,Ne)
    !----------------------------------------------------------

    select case (this%Nnode_h1D)
    case (2)
        call element_operation_kernel_matvec_divlike_var5_P1( &
          this%elem_optr_tensorprod3D_P1%D1D, this%elem_optr_tensorprod3D_P1%D1D_tr, this%elem_optr_tensorprod3D_P1%Lift_mat, &
          Flux_x, Flux_y,  Flux_z, ebnd_flux, &
          E11, E22, E33, Gsqrt, Ne, &
          div3D )
    case (3)
        call element_operation_kernel_matvec_divlike_var5_P2( &
          this%elem_optr_tensorprod3D_P2%D1D, this%elem_optr_tensorprod3D_P2%D1D_tr, this%elem_optr_tensorprod3D_P2%Lift_mat, &
          Flux_x, Flux_y,  Flux_z, ebnd_flux, &
          E11, E22, E33, Gsqrt, Ne, &
          div3D )
    case (4)
        call element_operation_kernel_matvec_divlike_var5_P3( &
          this%elem_optr_tensorprod3D_P3%D1D, this%elem_optr_tensorprod3D_P3%D1D_tr, this%elem_optr_tensorprod3D_P3%Lift_mat, &
          Flux_x, Flux_y,  Flux_z, ebnd_flux, &
          E11, E22, E33, Gsqrt, Ne, &
          div3D )
    case (5)
        call element_operation_kernel_matvec_divlike_var5_P4( &
          this%elem_optr_tensorprod3D_P4%D1D, this%elem_optr_tensorprod3D_P4%D1D_tr, this%elem_optr_tensorprod3D_P4%Lift_mat, &
          Flux_x, Flux_y,  Flux_z, ebnd_flux, &
          E11, E22, E33, Gsqrt, Ne, &
          div3D )
    case (6)
        call element_operation_kernel_matvec_divlike_var5_P5( &
          this%elem_optr_tensorprod3D_P5%D1D, this%elem_optr_tensorprod3D_P5%D1D_tr, this%elem_optr_tensorprod3D_P5%Lift_mat, &
          Flux_x, Flux_y,  Flux_z, ebnd_flux, &
          E11, E22, E33, Gsqrt, Ne, &
          div3D )
    case (7)
        call element_operation_kernel_matvec_divlike_var5_P6( &
          this%elem_optr_tensorprod3D_P6%D1D, this%elem_optr_tensorprod3D_P6%D1D_tr, this%elem_optr_tensorprod3D_P6%Lift_mat, &
          Flux_x, Flux_y,  Flux_z, ebnd_flux, &
          E11, E22, E33, Gsqrt, Ne, &
          div3D )
    case (8)
        call element_operation_kernel_matvec_divlike_var5_P7( &
          this%elem_optr_tensorprod3D_P7%D1D, this%elem_optr_tensorprod3D_P7%D1D_tr, this%elem_optr_tensorprod3D_P7%Lift_mat, &
          Flux_x, Flux_y,  Flux_z, ebnd_flux, &
          E11, E22, E33, Gsqrt, Ne, &
          div3D )
    case (9)
        call element_operation_kernel_matvec_divlike_var5_P8( &
          this%elem_optr_tensorprod3D_P8%D1D, this%elem_optr_tensorprod3D_P8%D1D_tr, this%elem_optr_tensorprod3D_P8%Lift_mat, &
          Flux_x, Flux_y,  Flux_z, ebnd_flux, &
          E11, E22, E33, Gsqrt, Ne, &
          div3D )
    case (10)
        call element_operation_kernel_matvec_divlike_var5_P9( &
          this%elem_optr_tensorprod3D_P9%D1D, this%elem_optr_tensorprod3D_P9%D1D_tr, this%elem_optr_tensorprod3D_P9%Lift_mat, &
          Flux_x, Flux_y,  Flux_z, ebnd_flux, &
          E11, E22, E33, Gsqrt, Ne, &
          div3D )
    case (11)
        call element_operation_kernel_matvec_divlike_var5_P10( &
          this%elem_optr_tensorprod3D_P10%D1D, this%elem_optr_tensorprod3D_P10%D1D_tr, this%elem_optr_tensorprod3D_P10%Lift_mat, &
          Flux_x, Flux_y,  Flux_z, ebnd_flux, &
          E11, E22, E33, Gsqrt, Ne, &
          div3D )
    case (12)
        call element_operation_kernel_matvec_divlike_var5_P11( &
          this%elem_optr_tensorprod3D_P11%D1D, this%elem_optr_tensorprod3D_P11%D1D_tr, this%elem_optr_tensorprod3D_P11%Lift_mat, &
          Flux_x, Flux_y,  Flux_z, ebnd_flux, &
          E11, E22, E33, Gsqrt, Ne, &
          div3D )
    case (13)
        call element_operation_kernel_matvec_divlike_var5_P12( &
          this%elem_optr_tensorprod3D_P12%D1D, this%elem_optr_tensorprod3D_P12%D1D_tr, this%elem_optr_tensorprod3D_P12%Lift_mat, &
          Flux_x, Flux_y,  Flux_z, ebnd_flux, &
          E11, E22, E33, Gsqrt, Ne, &
          div3D )
    case (14)
        call element_operation_kernel_matvec_divlike_var5_P13( &
          this%elem_optr_tensorprod3D_P13%D1D, this%elem_optr_tensorprod3D_P13%D1D_tr, this%elem_optr_tensorprod3D_P13%Lift_mat, &
          Flux_x, Flux_y,  Flux_z, ebnd_flux, &
          E11, E22, E33, Gsqrt, Ne, &
          div3D )
    case (15)
        call element_operation_kernel_matvec_divlike_var5_P14( &
          this%elem_optr_tensorprod3D_P14%D1D, this%elem_optr_tensorprod3D_P14%D1D_tr, this%elem_optr_tensorprod3D_P14%Lift_mat, &
          Flux_x, Flux_y,  Flux_z, ebnd_flux, &
          E11, E22, E33, Gsqrt, Ne, &
          div3D )
    case (16)
        call element_operation_kernel_matvec_divlike_var5_P15( &
          this%elem_optr_tensorprod3D_P15%D1D, this%elem_optr_tensorprod3D_P15%D1D_tr, this%elem_optr_tensorprod3D_P15%Lift_mat, &
          Flux_x, Flux_y,  Flux_z, ebnd_flux, &
          E11, E22, E33, Gsqrt, Ne, &
          div3D )
    end select
    return
  end subroutine ElementOperationGPU_DivVar5


!> Apply a modal filter for five variables
!!
  subroutine ElementOperationGPU_ModalFilter_var5( this, vec_in, vec_work, Ne, &
    vec_out )
    use scale_element_operation_tensorprod3D_kernel_gpu, only: &
      element_operation_kernel_matvec_ModalFilter_P15

    implicit none
    type(ElementOperationGPUDriver), intent(in) :: this
    integer, intent(in) :: Ne
    real(RP), intent(in) :: vec_in(this%Nnode_h1D**2*this%Nnode_v,Ne,5)
    real(RP), intent(out) :: vec_work(this%Nnode_h1D**2*this%Nnode_v,Ne)
    real(RP), intent(out) :: vec_out(this%Nnode_h1D**2*this%Nnode_v,Ne,5)
    integer :: iv
    !---------------------------------------------

    select case (this%Nnode_h1D)
    case (2)
      do iv=1, 5
        call element_operation_kernel_matvec_ModalFilter_P1( this%elem_optr_tensorprod3D_P1%MFilter_h1D, this%elem_optr_tensorprod3D_P1%MFilter_h1D_tr, this%elem_optr_tensorprod3D_P1%MFilter_v1D_tr, vec_in(:,:,iv), vec_work, Ne, &
          vec_out(:,:,iv) )
      end do
    case (3)
      do iv=1, 5
        call element_operation_kernel_matvec_ModalFilter_P2( this%elem_optr_tensorprod3D_P2%MFilter_h1D, this%elem_optr_tensorprod3D_P2%MFilter_h1D_tr, this%elem_optr_tensorprod3D_P2%MFilter_v1D_tr, vec_in(:,:,iv), vec_work, Ne, &
          vec_out(:,:,iv) )
      end do
    case (4)
      do iv=1, 5
        call element_operation_kernel_matvec_ModalFilter_P3( this%elem_optr_tensorprod3D_P3%MFilter_h1D, this%elem_optr_tensorprod3D_P3%MFilter_h1D_tr, this%elem_optr_tensorprod3D_P3%MFilter_v1D_tr, vec_in(:,:,iv), vec_work, Ne, &
          vec_out(:,:,iv) )
      end do
    case (5)
      do iv=1, 5
        call element_operation_kernel_matvec_ModalFilter_P4( this%elem_optr_tensorprod3D_P4%MFilter_h1D, this%elem_optr_tensorprod3D_P4%MFilter_h1D_tr, this%elem_optr_tensorprod3D_P4%MFilter_v1D_tr, vec_in(:,:,iv), vec_work, Ne, &
          vec_out(:,:,iv) )
      end do
    case (6)
      do iv=1, 5
        call element_operation_kernel_matvec_ModalFilter_P5( this%elem_optr_tensorprod3D_P5%MFilter_h1D, this%elem_optr_tensorprod3D_P5%MFilter_h1D_tr, this%elem_optr_tensorprod3D_P5%MFilter_v1D_tr, vec_in(:,:,iv), vec_work, Ne, &
          vec_out(:,:,iv) )
      end do
    case (7)
      do iv=1, 5
        call element_operation_kernel_matvec_ModalFilter_P6( this%elem_optr_tensorprod3D_P6%MFilter_h1D, this%elem_optr_tensorprod3D_P6%MFilter_h1D_tr, this%elem_optr_tensorprod3D_P6%MFilter_v1D_tr, vec_in(:,:,iv), vec_work, Ne, &
          vec_out(:,:,iv) )
      end do
    case (8)
      do iv=1, 5
        call element_operation_kernel_matvec_ModalFilter_P7( this%elem_optr_tensorprod3D_P7%MFilter_h1D, this%elem_optr_tensorprod3D_P7%MFilter_h1D_tr, this%elem_optr_tensorprod3D_P7%MFilter_v1D_tr, vec_in(:,:,iv), vec_work, Ne, &
          vec_out(:,:,iv) )
      end do
    case (9)
      do iv=1, 5
        call element_operation_kernel_matvec_ModalFilter_P8( this%elem_optr_tensorprod3D_P8%MFilter_h1D, this%elem_optr_tensorprod3D_P8%MFilter_h1D_tr, this%elem_optr_tensorprod3D_P8%MFilter_v1D_tr, vec_in(:,:,iv), vec_work, Ne, &
          vec_out(:,:,iv) )
      end do
    case (10)
      do iv=1, 5
        call element_operation_kernel_matvec_ModalFilter_P9( this%elem_optr_tensorprod3D_P9%MFilter_h1D, this%elem_optr_tensorprod3D_P9%MFilter_h1D_tr, this%elem_optr_tensorprod3D_P9%MFilter_v1D_tr, vec_in(:,:,iv), vec_work, Ne, &
          vec_out(:,:,iv) )
      end do
    case (11)
      do iv=1, 5
        call element_operation_kernel_matvec_ModalFilter_P10( this%elem_optr_tensorprod3D_P10%MFilter_h1D, this%elem_optr_tensorprod3D_P10%MFilter_h1D_tr, this%elem_optr_tensorprod3D_P10%MFilter_v1D_tr, vec_in(:,:,iv), vec_work, Ne, &
          vec_out(:,:,iv) )
      end do
    case (12)
      do iv=1, 5
        call element_operation_kernel_matvec_ModalFilter_P11( this%elem_optr_tensorprod3D_P11%MFilter_h1D, this%elem_optr_tensorprod3D_P11%MFilter_h1D_tr, this%elem_optr_tensorprod3D_P11%MFilter_v1D_tr, vec_in(:,:,iv), vec_work, Ne, &
          vec_out(:,:,iv) )
      end do
    case (13)
      do iv=1, 5
        call element_operation_kernel_matvec_ModalFilter_P12( this%elem_optr_tensorprod3D_P12%MFilter_h1D, this%elem_optr_tensorprod3D_P12%MFilter_h1D_tr, this%elem_optr_tensorprod3D_P12%MFilter_v1D_tr, vec_in(:,:,iv), vec_work, Ne, &
          vec_out(:,:,iv) )
      end do
    case (14)
      do iv=1, 5
        call element_operation_kernel_matvec_ModalFilter_P13( this%elem_optr_tensorprod3D_P13%MFilter_h1D, this%elem_optr_tensorprod3D_P13%MFilter_h1D_tr, this%elem_optr_tensorprod3D_P13%MFilter_v1D_tr, vec_in(:,:,iv), vec_work, Ne, &
          vec_out(:,:,iv) )
      end do
    case (15)
      do iv=1, 5
        call element_operation_kernel_matvec_ModalFilter_P14( this%elem_optr_tensorprod3D_P14%MFilter_h1D, this%elem_optr_tensorprod3D_P14%MFilter_h1D_tr, this%elem_optr_tensorprod3D_P14%MFilter_v1D_tr, vec_in(:,:,iv), vec_work, Ne, &
          vec_out(:,:,iv) )
      end do
    case (16)
      do iv=1, 5
        call element_operation_kernel_matvec_ModalFilter_P15( this%elem_optr_tensorprod3D_P15%MFilter_h1D, this%elem_optr_tensorprod3D_P15%MFilter_h1D_tr, this%elem_optr_tensorprod3D_P15%MFilter_v1D_tr, vec_in(:,:,iv), vec_work, Ne, &
          vec_out(:,:,iv) )
      end do
    end select
    return
  end subroutine ElementOperationGPU_ModalFilter_var5

end module scale_element_operation_gpu_driver
