&PARAM_TEST
  NprcX = 1, 
  NeGX  = 8, 
  NprcY = 1, 
  NeGY  = 8, 
  PolyOrder = 7,
/
&PARAM_Poisson2D_MG
  !- 
  H_LEVEL_NUM = 3, 
  NeGX_list = 8, 4, 2,
  NeGY_list = 8, 4, 2,
  H_ITR_NUM_list = 30, 30, 30,
!  H_LEVEL_NUM = 2, 
!  NeGX_list = 8, 4,
!  NeGY_list = 8, 4,  
!  H_ITR_NUM_list = 20, 20,  
!  H_LEVEL_NUM = 1, 
!  NeGX_list = 8,  
!  NeGY_list = 8,  
!  H_ITR_NUM_list = 10, 
  !-
!  P_LEVEL_NUM = 1, 
!  P_LEVEL_LIST = 7, 
!  P_ITR_NUM_list = 10,
!-
!  P_LEVEL_NUM = 2, 
!  P_LEVEL_LIST = 7,,3, 
!  P_ITR_NUM_list = 5,5,
!-
  P_LEVEL_NUM = 3,
  P_LEVEL_LIST = 7, 3, 1,
  P_ITR_NUM_list = 5, 5, 5,
/
&PARAM_TIME
  TIME_DURATION                 = 1D0, 
  TIME_DURATION_UNIT            = 'SEC', 
  TIME_DT                       = 1D0, 
  TIME_DT_UNIT                  = 'SEC', 
/
&PARAM_FILE_HISTORY
 FILE_HISTORY_DEFAULT_BASENAME  = "history",
 FILE_HISTORY_DEFAULT_TINTERVAL = 1D0,
 FILE_HISTORY_DEFAULT_TUNIT     = "SEC",
 FILE_HISTORY_DEFAULT_TAVERAGE  = .false.,
 FILE_HISTORY_DEFAULT_DATATYPE  = "REAL4",
 FILE_HISTORY_OUTPUT_STEP0      = .true.,
/
&HISTORY_ITEM name='q'         /
&HISTORY_ITEM name='qexact'    /
&HISTORY_ITEM name='f'         /
