!-------------------------------------------------------------------------------
! Warning: This file was generated from common/scale_timeint_rk.F90.erb.
!          Do not edit this file.
!-------------------------------------------------------------------------------
!-------------------------------------------------------------------------------
!> module common / Runge-Kutta scheme 
!!
!! @par Description
!!      Driver module to provide various Runge-Kutta schemes. 
!!
!! @author Team SCALE
!<
#include "scaleFElib.h"
module scale_timeint_rk
  !-----------------------------------------------------------------------------
  !
  !++ Used modules
  !
  use scale_precision
  use scale_io
  use scale_prc
  use scale_prof

  !-----------------------------------------------------------------------------
  implicit none
  private

  !-----------------------------------------------------------------------------
  !
  !++ Public type, procedures
  !
  type, public :: timeint_rk
    real(RP), private :: dt

    integer, private :: rk_scheme_id_ex
    integer, private :: rk_scheme_id_im

    integer, public :: var_num
    integer, private, allocatable :: size_each_var(:)
    integer, public :: nstage
    integer, public :: var_buf_size
    integer, public :: tend_buf_size

    ! For Butcher representation (explicit part)
    real(RP), public, allocatable :: coef_a_ex(:,:)
    real(RP), public, allocatable :: coef_b_ex(:)
    real(RP), public, allocatable :: coef_c_ex(:)

    ! For Shu-Osher representation (explicit part)
    real(RP), public, allocatable :: coef_sig_ex(:,:)
    real(RP), public, allocatable :: coef_gam_ex(:,:)

    ! For Butcher representation (implicit part)
    real(RP), public, allocatable :: coef_a_im(:,:)
    real(RP), public, allocatable :: coef_b_im(:)
    real(RP), public, allocatable :: coef_c_im(:)

    integer, allocatable :: tend_buf_indmap(:)
    real(RP), public, allocatable :: var_buf1D_ex(:,:,:)
    real(RP), public, allocatable :: tend_buf1D_ex(:,:,:)
    real(RP), public, allocatable :: tend_buf1D_im(:,:,:)
    real(RP), private, allocatable :: var0_1D(:,:)
    real(RP), private, allocatable :: varTmp_1D(:,:)    
    real(RP), public, allocatable :: var_buf2D_ex(:,:,:,:)
    real(RP), public, allocatable :: tend_buf2D_ex(:,:,:,:)
    real(RP), public, allocatable :: tend_buf2D_im(:,:,:,:)
    real(RP), private, allocatable :: var0_2D(:,:,:)
    real(RP), private, allocatable :: varTmp_2D(:,:,:)    
    real(RP), public, allocatable :: var_buf3D_ex(:,:,:,:,:)
    real(RP), public, allocatable :: tend_buf3D_ex(:,:,:,:,:)
    real(RP), public, allocatable :: tend_buf3D_im(:,:,:,:,:)
    real(RP), private, allocatable :: var0_3D(:,:,:,:)
    real(RP), private, allocatable :: varTmp_3D(:,:,:,:)    

    logical, private :: low_storage_flag
    logical, public :: imex_flag
    integer, public :: ndim
  contains
    procedure, public :: Init => timeint_rk_Init
    procedure, public :: Final => timeint_rk_Final
    procedure, public :: Get_implicit_diagfac => timeint_rk_Get_implicit_diagfac 
    procedure, public :: Get_deltime => timeint_rk_Get_deltime
    procedure, public :: Advance1D => timeint_rk_advance1D
    procedure, public :: StoreImplicit1D => timeint_rk_storeimpl1D
    procedure, public :: Advance2D => timeint_rk_advance2D
    procedure, public :: StoreImplicit2D => timeint_rk_storeimpl2D
    procedure, public :: Advance3D => timeint_rk_advance3D
    procedure, public :: StoreImplicit3D => timeint_rk_storeimpl3D
    generic, public :: Advance => Advance1D, Advance2D, Advance3D
    generic, public :: StoreImplicit => StoreImplicit1D, StoreImplicit2D, StoreImplicit3D
  end type timeint_rk

  !-----------------------------------------------------------------------------
  !
  !++ Public parameters & variables
  !
  !-----------------------------------------------------------------------------
  !
  !++ Private procedures
  !
  !-------------------

contains

!----------------

  subroutine timeint_rk_Init( this,                  &
    rk_scheme_name, dt, var_num, ndim, size_each_var )

    use scale_timeint_rk_butcher_tab, only: &
      timeint_rk_butcher_tab_get_info,      &
      timeint_rk_butcher_tab_get      
    implicit none
    class(timeint_rk), intent(inout) :: this
    character(*), intent(in) :: rk_scheme_name
    real(RP), intent(in) :: dt
    integer, intent(in) :: var_num
    integer, intent(in) :: ndim
    integer, intent(in) :: size_each_var(ndim)
    !----------------------------------------

    this%dt = dt
    this%ndim = ndim
    this%var_num  = 1
    allocate( this%size_each_var(ndim) )
    this%size_each_var(:) = size_each_var(:)

    call timeint_rk_butcher_tab_get_info( rk_scheme_name, & ! (in)
      this%nstage, this%tend_buf_size,                    & ! (out)
      this%low_storage_flag, this%imex_flag               ) ! (out)
    
    allocate ( this%coef_a_ex(this%nstage,this%nstage), this%coef_b_ex(this%nstage), this%coef_c_ex(this%nstage) )
    allocate ( this%coef_sig_ex(this%nstage+1,this%nstage), this%coef_gam_ex(this%nstage+1,this%nstage) )
    if (this%imex_flag) then
      allocate ( this%coef_a_im(this%nstage,this%nstage), this%coef_b_im(this%nstage), this%coef_c_im(this%nstage) )
    end if

    select case(this%ndim)
    case(1)
      allocate( this%tend_buf1D_ex(size_each_var(1), var_num, this%tend_buf_size) )
      if ( this%imex_flag ) then
        allocate( this%tend_buf1D_im(size_each_var(1), var_num, this%tend_buf_size) )
      end if
      allocate( this%var0_1D(size_each_var(1), var_num) )
      allocate( this%varTmp_1D(size_each_var(1), var_num) ) 
    case(2)
      allocate( this%tend_buf2D_ex(size_each_var(1),size_each_var(2), var_num, this%tend_buf_size) )
      if ( this%imex_flag ) then
        allocate( this%tend_buf2D_im(size_each_var(1),size_each_var(2), var_num, this%tend_buf_size) )
      end if
      allocate( this%var0_2D(size_each_var(1),size_each_var(2), var_num) )
      allocate( this%varTmp_2D(size_each_var(1),size_each_var(2), var_num) ) 
    case(3)
      allocate( this%tend_buf3D_ex(size_each_var(1),size_each_var(2),size_each_var(3), var_num, this%tend_buf_size) )
      if ( this%imex_flag ) then
        allocate( this%tend_buf3D_im(size_each_var(1),size_each_var(2),size_each_var(3), var_num, this%tend_buf_size) )
      end if
      allocate( this%var0_3D(size_each_var(1),size_each_var(2),size_each_var(3), var_num) )
      allocate( this%varTmp_3D(size_each_var(1),size_each_var(2),size_each_var(3), var_num) ) 
    end select
    allocate( this%tend_buf_indmap(this%nstage) )

    call timeint_rk_butcher_tab_get( &
      rk_scheme_name, this%nstage, this%imex_flag,    & ! (in)
      this%coef_a_ex, this%coef_b_ex, this%coef_c_ex, & ! (out)
      this%coef_sig_ex, this%coef_gam_ex,             & ! (out)
      this%coef_a_im, this%coef_b_im, this%coef_c_im, & ! (out)
      this%tend_buf_indmap                            ) ! (out)

    return
  end subroutine timeint_rk_Init

  subroutine timeint_rk_Final( this )

    class(timeint_rk), intent(inout) :: this
    !----------------------------------------
    
    deallocate( this%coef_a_ex, this%coef_b_ex, this%coef_c_ex )
    if (this%imex_flag) then
      deallocate( this%coef_a_im, this%coef_b_im, this%coef_c_im )
    end if

    select case(this%ndim)
    case(1)
      deallocate( this%var0_1d )
      deallocate( this%tend_buf1D_ex )
      if (this%imex_flag) deallocate( this%tend_buf1D_im )
      deallocate( this%varTmp_1d )
    case(2)
      deallocate( this%var0_2d )
      deallocate( this%tend_buf2D_ex )
      if (this%imex_flag) deallocate( this%tend_buf2D_im )
      deallocate( this%varTmp_2d )
    case(3)
      deallocate( this%var0_3d )
      deallocate( this%tend_buf3D_ex )
      if (this%imex_flag) deallocate( this%tend_buf3D_im )
      deallocate( this%varTmp_3d )
    end select
    
    return
  end subroutine timeint_rk_Final

  elemental function timeint_rk_Get_DelTime( this ) result(dt)
    implicit none
    class(timeint_rk), intent(in) :: this
    real(RP) :: dt
    !-----------------------------------------------------
    
    dt = this%dt

    return
  end function timeint_rk_Get_DelTime

  elemental function timeint_rk_Get_implicit_diagfac( this, nowstage ) result(fac)
    implicit none
    class(timeint_rk), intent(in) :: this
    integer, intent(in) :: nowstage
    real(RP) :: fac
    !-----------------------------------------------------
    
    fac = this%coef_a_im(nowstage,nowstage) * this%dt

    return
  end function timeint_rk_Get_implicit_diagfac
  !----------------


  subroutine timeint_rk_advance1D( this, nowstage, q, varID, is, ie )
    class(timeint_rk), intent(inout) :: this
    integer, intent(in) :: nowstage
    real(RP), intent(inout) :: q(:)
    integer, intent(in) :: varID
    integer, intent(in) :: is, ie 

    !----------------------------------------    
 
    if (this%low_storage_flag) then
      call rk_advance_low_storage1D( this, nowstage, q, varID, is, ie )
    else
      call rk_advance_general1D( this, nowstage, q, varID, is, ie  )
    end if

    return
  end subroutine timeint_rk_advance1D

  subroutine timeint_rk_storeimpl1D( this, nowstage, q, varID, is, ie )
    class(timeint_rk), intent(inout) :: this
    integer, intent(in) :: nowstage
    real(RP), intent(inout) :: q(:)
    integer, intent(in) :: varID
    integer, intent(in) :: is, ie 

    !----------------------------------------    
 
    call rk_storeimpl_general1D( this, nowstage, q, varID, is, ie  )

    return
  end subroutine timeint_rk_storeimpl1D

  subroutine timeint_rk_advance2D( this, nowstage, q, varID, is, ie ,js, je )
    class(timeint_rk), intent(inout) :: this
    integer, intent(in) :: nowstage
    real(RP), intent(inout) :: q(:,:)
    integer, intent(in) :: varID
    integer, intent(in) :: is, ie ,js, je 

    !----------------------------------------    
 
    if (this%low_storage_flag) then
      call rk_advance_low_storage2D( this, nowstage, q, varID, is, ie ,js, je )
    else
      call rk_advance_general2D( this, nowstage, q, varID, is, ie ,js, je  )
    end if

    return
  end subroutine timeint_rk_advance2D

  subroutine timeint_rk_storeimpl2D( this, nowstage, q, varID, is, ie ,js, je )
    class(timeint_rk), intent(inout) :: this
    integer, intent(in) :: nowstage
    real(RP), intent(inout) :: q(:,:)
    integer, intent(in) :: varID
    integer, intent(in) :: is, ie ,js, je 

    !----------------------------------------    
 
    call rk_storeimpl_general2D( this, nowstage, q, varID, is, ie ,js, je  )

    return
  end subroutine timeint_rk_storeimpl2D

  subroutine timeint_rk_advance3D( this, nowstage, q, varID, is, ie ,js, je ,ks, ke )
    class(timeint_rk), intent(inout) :: this
    integer, intent(in) :: nowstage
    real(RP), intent(inout) :: q(:,:,:)
    integer, intent(in) :: varID
    integer, intent(in) :: is, ie ,js, je ,ks, ke 

    !----------------------------------------    
 
    if (this%low_storage_flag) then
      call rk_advance_low_storage3D( this, nowstage, q, varID, is, ie ,js, je ,ks, ke )
    else
      call rk_advance_general3D( this, nowstage, q, varID, is, ie ,js, je ,ks, ke  )
    end if

    return
  end subroutine timeint_rk_advance3D

  subroutine timeint_rk_storeimpl3D( this, nowstage, q, varID, is, ie ,js, je ,ks, ke )
    class(timeint_rk), intent(inout) :: this
    integer, intent(in) :: nowstage
    real(RP), intent(inout) :: q(:,:,:)
    integer, intent(in) :: varID
    integer, intent(in) :: is, ie ,js, je ,ks, ke 

    !----------------------------------------    
 
    call rk_storeimpl_general3D( this, nowstage, q, varID, is, ie ,js, je ,ks, ke  )

    return
  end subroutine timeint_rk_storeimpl3D

!-------------------



!OCL SERIAL
  subroutine rk_advance_low_storage1D( this, nowstage, q, varID, is, ie  )
    use scale_const, only: &
      EPS => CONST_EPS
    class(timeint_rk), intent(inout) :: this
    integer, intent(in) :: nowstage
    real(RP), intent(inout) :: q(:)
    integer, intent(in) :: varID
    integer, intent(in) :: is, ie 

    integer :: i
    real(RP) :: sig_ss
    real(RP) :: gam_ss
    real(RP) :: one_Minus_sig_ss
    real(RP) :: sig_Ns
    real(RP) :: gam_Ns

    !----------------------------------------    

    call PROF_rapstart( 'rk_advance_low_storage1D', 3) 

    sig_ss = this%coef_sig_ex(nowstage+1,nowstage)
    sig_Ns = this%coef_sig_ex(this%nstage+1,nowstage)
    one_Minus_sig_ss = 1.0_RP - sig_ss
    gam_ss = this%dt * this%coef_gam_ex(nowstage+1,nowstage)
    gam_Ns = this%dt * this%coef_gam_ex(this%nstage+1,nowstage)

    if ( nowstage == this%nstage ) then
      !$omp parallel private(i)
      !$omp do
      do i=is, ie
        q(i) =  this%varTmp_1d(i,varID)                                             &
                + sig_ss * q(i) + gam_ss * this%tend_buf1D_ex(i,varID,1)
      end do
      !$omp end parallel
      call PROF_rapend( 'rk_advance_low_storage1D', 3)

      return
    end if
      
    !$omp parallel private(i)
    if (nowstage == 1) then
      !$omp do
      do i=is, ie
        this%var0_1D(i,varID)   = q(i)
        this%varTmp_1D(i,varID) = 0.0_RP
      end do
    end if

    if ( abs(sig_Ns) > EPS .or. abs(gam_Ns) > EPS ) then
      !$omp do
      do i=is, ie
        this%varTmp_1d(i,varID) = this%varTmp_1d(i,varID)      &
            + sig_Ns * q(i) + gam_Ns * this%tend_buf1D_ex(i,varID,1)
      end do
    end if

    !$omp do
    do i=is, ie
      q(i) = one_Minus_sig_ss * this%var0_1d(i,varID)                &
              + sig_ss * q(i) + gam_ss * this%tend_buf1D_ex(i,varID,1)
    end do

    !$omp end parallel

    call PROF_rapend( 'rk_advance_low_storage1D', 3)

    return
  end subroutine rk_advance_low_storage1D


!OCL SERIAL
  subroutine rk_advance_low_storage2D( this, nowstage, q, varID, is, ie ,js, je  )
    use scale_const, only: &
      EPS => CONST_EPS
    class(timeint_rk), intent(inout) :: this
    integer, intent(in) :: nowstage
    real(RP), intent(inout) :: q(:,:)
    integer, intent(in) :: varID
    integer, intent(in) :: is, ie ,js, je 

    integer :: i,j
    real(RP) :: sig_ss
    real(RP) :: gam_ss
    real(RP) :: one_Minus_sig_ss
    real(RP) :: sig_Ns
    real(RP) :: gam_Ns

    !----------------------------------------    

    call PROF_rapstart( 'rk_advance_low_storage2D', 3) 

    sig_ss = this%coef_sig_ex(nowstage+1,nowstage)
    sig_Ns = this%coef_sig_ex(this%nstage+1,nowstage)
    one_Minus_sig_ss = 1.0_RP - sig_ss
    gam_ss = this%dt * this%coef_gam_ex(nowstage+1,nowstage)
    gam_Ns = this%dt * this%coef_gam_ex(this%nstage+1,nowstage)

    if ( nowstage == this%nstage ) then
      !$omp parallel private(i,j)
      !$omp do
      do j=js, je
      do i=is, ie
        q(i,j) =  this%varTmp_2d(i,j,varID)                                             &
                + sig_ss * q(i,j) + gam_ss * this%tend_buf2D_ex(i,j,varID,1)
      end do
      end do
      !$omp end parallel
      call PROF_rapend( 'rk_advance_low_storage2D', 3)

      return
    end if
      
    !$omp parallel private(i,j)
    if (nowstage == 1) then
      !$omp do
      do j=js, je
      do i=is, ie
        this%var0_2D(i,j,varID)   = q(i,j)
        this%varTmp_2D(i,j,varID) = 0.0_RP
      end do
      end do
    end if

    if ( abs(sig_Ns) > EPS .or. abs(gam_Ns) > EPS ) then
      !$omp do
      do j=js, je
      do i=is, ie
        this%varTmp_2d(i,j,varID) = this%varTmp_2d(i,j,varID)      &
            + sig_Ns * q(i,j) + gam_Ns * this%tend_buf2D_ex(i,j,varID,1)
      end do
      end do
    end if

    !$omp do
    do j=js, je
    do i=is, ie
      q(i,j) = one_Minus_sig_ss * this%var0_2d(i,j,varID)                &
              + sig_ss * q(i,j) + gam_ss * this%tend_buf2D_ex(i,j,varID,1)
    end do
    end do

    !$omp end parallel

    call PROF_rapend( 'rk_advance_low_storage2D', 3)

    return
  end subroutine rk_advance_low_storage2D


!OCL SERIAL
  subroutine rk_advance_low_storage3D( this, nowstage, q, varID, is, ie ,js, je ,ks, ke  )
    use scale_const, only: &
      EPS => CONST_EPS
    class(timeint_rk), intent(inout) :: this
    integer, intent(in) :: nowstage
    real(RP), intent(inout) :: q(:,:,:)
    integer, intent(in) :: varID
    integer, intent(in) :: is, ie ,js, je ,ks, ke 

    integer :: i,j,k
    real(RP) :: sig_ss
    real(RP) :: gam_ss
    real(RP) :: one_Minus_sig_ss
    real(RP) :: sig_Ns
    real(RP) :: gam_Ns

    !----------------------------------------    

    call PROF_rapstart( 'rk_advance_low_storage3D', 3) 

    sig_ss = this%coef_sig_ex(nowstage+1,nowstage)
    sig_Ns = this%coef_sig_ex(this%nstage+1,nowstage)
    one_Minus_sig_ss = 1.0_RP - sig_ss
    gam_ss = this%dt * this%coef_gam_ex(nowstage+1,nowstage)
    gam_Ns = this%dt * this%coef_gam_ex(this%nstage+1,nowstage)

    if ( nowstage == this%nstage ) then
      !$omp parallel private(i,j,k)
      !$omp do collapse(2)
      do k=ks, ke
      do j=js, je
      do i=is, ie
        q(i,j,k) =  this%varTmp_3d(i,j,k,varID)                                             &
                + sig_ss * q(i,j,k) + gam_ss * this%tend_buf3D_ex(i,j,k,varID,1)
      end do
      end do
      end do
      !$omp end parallel
      call PROF_rapend( 'rk_advance_low_storage3D', 3)

      return
    end if
      
    !$omp parallel private(i,j,k)
    if (nowstage == 1) then
      !$omp do collapse(2)
      do k=ks, ke
      do j=js, je
      do i=is, ie
        this%var0_3D(i,j,k,varID)   = q(i,j,k)
        this%varTmp_3D(i,j,k,varID) = 0.0_RP
      end do
      end do
      end do
    end if

    if ( abs(sig_Ns) > EPS .or. abs(gam_Ns) > EPS ) then
      !$omp do collapse(2)
      do k=ks, ke
      do j=js, je
      do i=is, ie
        this%varTmp_3d(i,j,k,varID) = this%varTmp_3d(i,j,k,varID)      &
            + sig_Ns * q(i,j,k) + gam_Ns * this%tend_buf3D_ex(i,j,k,varID,1)
      end do
      end do
      end do
    end if

    !$omp do collapse(2)
    do k=ks, ke
    do j=js, je
    do i=is, ie
      q(i,j,k) = one_Minus_sig_ss * this%var0_3d(i,j,k,varID)                &
              + sig_ss * q(i,j,k) + gam_ss * this%tend_buf3D_ex(i,j,k,varID,1)
    end do
    end do
    end do

    !$omp end parallel

    call PROF_rapend( 'rk_advance_low_storage3D', 3)

    return
  end subroutine rk_advance_low_storage3D


!OCL SERIAL
  subroutine rk_advance_general1D( this, nowstage, q, varID, is, ie  )
    class(timeint_rk), intent(inout) :: this
    integer, intent(in) :: nowstage
    real(RP), intent(inout) :: q(:)
    integer, intent(in) :: varID
    integer, intent(in) :: is, ie 

    integer :: i
    integer :: s
    integer :: tintbuf_ind
    !----------------------------------------    

    call PROF_rapstart( 'rk_advance_generall1D', 3)

    tintbuf_ind = this%tend_buf_indmap(nowstage)

    if ( this%nstage == 1 ) then
      !$omp parallel do
      do i=is, ie
        this%varTmp_1d(i,varID) = q(i)
      end do
    end if

    if ( nowstage ==  this%nstage ) then
      if ( this%imex_flag ) then

      !$omp parallel do
        do i=is, ie
          q(i) =  this%varTmp_1d(i,varID) + this%dt * ( &
              + this%coef_b_ex(nowstage) * this%tend_buf1D_ex(i,varID,tintbuf_ind)   & 
              + this%coef_b_im(nowstage) * this%tend_buf1D_im(i,varID,tintbuf_ind)   )
        end do
      else

        !$omp parallel do
        do i=is, ie
          q(i) =  this%varTmp_1d(i,varID)                                             &
                  + this%dt * this%coef_b_ex(nowstage) * this%tend_buf1D_ex(i,varID,tintbuf_ind)
        end do
      end if    
      call PROF_rapend( 'rk_advance_generall1D', 3)

      return
    end if 

    !$omp parallel private( s ) &
    !$omp private( i )

    if ( nowstage == 1 .and. (.not. this%imex_flag) ) then
      !$omp do
      do i=is, ie
        this%var0_1D(i,varID) = q(i)
        this%varTmp_1D(i,varID) = q(i)
      end do
    end if 

    if ( this%imex_flag ) then
      !$omp do
      do i=is, ie
        q(i) = this%var0_1d(i,varID)
        this%varTmp_1d(i,varID) =  this%varTmp_1d(i,varID) + this%dt * ( &
              + this%coef_b_ex(nowstage) * this%tend_buf1D_ex(i,varID,tintbuf_ind)   & 
              + this%coef_b_im(nowstage) * this%tend_buf1D_im(i,varID,tintbuf_ind)   )
      end do
    else
      !$omp do
      do i=is, ie
        q(i) = this%var0_1d(i,varID)
        this%varTmp_1d(i,varID) =  this%varTmp_1d(i,varID)                                             &
                  + this%dt * this%coef_b_ex(nowstage) * this%tend_buf1D_ex(i,varID,tintbuf_ind)
      end do
    end if 

    if ( this%tend_buf_size == 1 .and. (.not. this%imex_flag) ) then
      !$omp do
      do i=is, ie
        q(i) = this%var0_1d(i,varID)                                                &
            +  this%dt * this%coef_a_ex(nowstage+1,nowstage)*this%tend_buf1D_ex(i,varID,1)
      end do
    else if ( .not. this%imex_flag ) then      
      do s=1, nowstage
      !$omp do
      do i=is, ie
        q(i) = q(i)                                  &
            +  this%dt * this%coef_a_ex(nowstage+1,s)*this%tend_buf1D_ex(i,varID,s)
      end do
      end do
    else ! IMEX   
      do s=1, nowstage
      !$omp do
      do i=is, ie
        q(i) = q(i)                                        &
            +  this%dt * ( this%coef_a_ex(nowstage+1,s)*this%tend_buf1D_ex(i,varID,s)  &
                         + this%coef_a_im(nowstage+1,s)*this%tend_buf1D_im(i,varID,s)  )                         
      end do
      end do
    end if

    !$omp end parallel
    call PROF_rapend( 'rk_advance_generall1D', 3)

    return
  end subroutine rk_advance_general1D

!OCL SERIAL
  subroutine rk_storeimpl_general1D( this, nowstage, q, varID, is, ie  )
    class(timeint_rk), intent(inout) :: this
    integer, intent(in) :: nowstage
    real(RP), intent(inout) :: q(:)
    integer, intent(in) :: varID
    integer, intent(in) :: is, ie 

    integer :: i
    integer :: tintbuf_ind
    !----------------------------------------    

    if (.not. this%imex_flag ) return
    
    tintbuf_ind = this%tend_buf_indmap(nowstage)   

    !$omp parallel

    if ( nowstage == 1 ) then
      !$omp do
      do i=is, ie
        this%var0_1D(i,varID) = q(i)
        this%varTmp_1D(i,varID) = q(i)
      end do
    end if
            
    !$omp do
    do i=is, ie
      q(i) = q(i)                                                                              &
            +  this%dt * this%coef_a_im(nowstage,nowstage)*this%tend_buf1D_im(i,varID,tintbuf_ind)  
    end do
    !$omp end parallel

    return
  end subroutine rk_storeimpl_general1D
 

!OCL SERIAL
  subroutine rk_advance_general2D( this, nowstage, q, varID, is, ie ,js, je  )
    class(timeint_rk), intent(inout) :: this
    integer, intent(in) :: nowstage
    real(RP), intent(inout) :: q(:,:)
    integer, intent(in) :: varID
    integer, intent(in) :: is, ie ,js, je 

    integer :: i,j
    integer :: s
    integer :: tintbuf_ind
    !----------------------------------------    

    call PROF_rapstart( 'rk_advance_generall2D', 3)

    tintbuf_ind = this%tend_buf_indmap(nowstage)

    if ( this%nstage == 1 ) then
      !$omp parallel do
      do j=js, je
      do i=is, ie
        this%varTmp_2d(i,j,varID) = q(i,j)
      end do
      end do
    end if

    if ( nowstage ==  this%nstage ) then
      if ( this%imex_flag ) then

      !$omp parallel do
        do j=js, je
        do i=is, ie
          q(i,j) =  this%varTmp_2d(i,j,varID) + this%dt * ( &
              + this%coef_b_ex(nowstage) * this%tend_buf2D_ex(i,j,varID,tintbuf_ind)   & 
              + this%coef_b_im(nowstage) * this%tend_buf2D_im(i,j,varID,tintbuf_ind)   )
        end do
        end do
      else

        !$omp parallel do
        do j=js, je
        do i=is, ie
          q(i,j) =  this%varTmp_2d(i,j,varID)                                             &
                  + this%dt * this%coef_b_ex(nowstage) * this%tend_buf2D_ex(i,j,varID,tintbuf_ind)
        end do
        end do
      end if    
      call PROF_rapend( 'rk_advance_generall2D', 3)

      return
    end if 

    !$omp parallel private( s ) &
    !$omp private( i,j )

    if ( nowstage == 1 .and. (.not. this%imex_flag) ) then
      !$omp do
      do j=js, je
      do i=is, ie
        this%var0_2D(i,j,varID) = q(i,j)
        this%varTmp_2D(i,j,varID) = q(i,j)
      end do
      end do
    end if 

    if ( this%imex_flag ) then
      !$omp do
      do j=js, je
      do i=is, ie
        q(i,j) = this%var0_2d(i,j,varID)
        this%varTmp_2d(i,j,varID) =  this%varTmp_2d(i,j,varID) + this%dt * ( &
              + this%coef_b_ex(nowstage) * this%tend_buf2D_ex(i,j,varID,tintbuf_ind)   & 
              + this%coef_b_im(nowstage) * this%tend_buf2D_im(i,j,varID,tintbuf_ind)   )
      end do
      end do
    else
      !$omp do
      do j=js, je
      do i=is, ie
        q(i,j) = this%var0_2d(i,j,varID)
        this%varTmp_2d(i,j,varID) =  this%varTmp_2d(i,j,varID)                                             &
                  + this%dt * this%coef_b_ex(nowstage) * this%tend_buf2D_ex(i,j,varID,tintbuf_ind)
      end do
      end do
    end if 

    if ( this%tend_buf_size == 1 .and. (.not. this%imex_flag) ) then
      !$omp do
      do j=js, je
      do i=is, ie
        q(i,j) = this%var0_2d(i,j,varID)                                                &
            +  this%dt * this%coef_a_ex(nowstage+1,nowstage)*this%tend_buf2D_ex(i,j,varID,1)
      end do
      end do
    else if ( .not. this%imex_flag ) then      
      do s=1, nowstage
      !$omp do
      do j=js, je
      do i=is, ie
        q(i,j) = q(i,j)                                  &
            +  this%dt * this%coef_a_ex(nowstage+1,s)*this%tend_buf2D_ex(i,j,varID,s)
      end do
      end do
      end do
    else ! IMEX   
      do s=1, nowstage
      !$omp do
      do j=js, je
      do i=is, ie
        q(i,j) = q(i,j)                                        &
            +  this%dt * ( this%coef_a_ex(nowstage+1,s)*this%tend_buf2D_ex(i,j,varID,s)  &
                         + this%coef_a_im(nowstage+1,s)*this%tend_buf2D_im(i,j,varID,s)  )                         
      end do
      end do
      end do
    end if

    !$omp end parallel
    call PROF_rapend( 'rk_advance_generall2D', 3)

    return
  end subroutine rk_advance_general2D

!OCL SERIAL
  subroutine rk_storeimpl_general2D( this, nowstage, q, varID, is, ie ,js, je  )
    class(timeint_rk), intent(inout) :: this
    integer, intent(in) :: nowstage
    real(RP), intent(inout) :: q(:,:)
    integer, intent(in) :: varID
    integer, intent(in) :: is, ie ,js, je 

    integer :: i,j
    integer :: tintbuf_ind
    !----------------------------------------    

    if (.not. this%imex_flag ) return
    
    tintbuf_ind = this%tend_buf_indmap(nowstage)   

    !$omp parallel

    if ( nowstage == 1 ) then
      !$omp do
      do j=js, je
      do i=is, ie
        this%var0_2D(i,j,varID) = q(i,j)
        this%varTmp_2D(i,j,varID) = q(i,j)
      end do
      end do
    end if
            
    !$omp do
    do j=js, je
    do i=is, ie
      q(i,j) = q(i,j)                                                                              &
            +  this%dt * this%coef_a_im(nowstage,nowstage)*this%tend_buf2D_im(i,j,varID,tintbuf_ind)  
    end do
    end do
    !$omp end parallel

    return
  end subroutine rk_storeimpl_general2D
 

!OCL SERIAL
  subroutine rk_advance_general3D( this, nowstage, q, varID, is, ie ,js, je ,ks, ke  )
    class(timeint_rk), intent(inout) :: this
    integer, intent(in) :: nowstage
    real(RP), intent(inout) :: q(:,:,:)
    integer, intent(in) :: varID
    integer, intent(in) :: is, ie ,js, je ,ks, ke 

    integer :: i,j,k
    integer :: s
    integer :: tintbuf_ind
    !----------------------------------------    

    call PROF_rapstart( 'rk_advance_generall3D', 3)

    tintbuf_ind = this%tend_buf_indmap(nowstage)

    if ( this%nstage == 1 ) then
      !$omp parallel do collapse(2)
      do k=ks, ke
      do j=js, je
      do i=is, ie
        this%varTmp_3d(i,j,k,varID) = q(i,j,k)
      end do
      end do
      end do
    end if

    if ( nowstage ==  this%nstage ) then
      if ( this%imex_flag ) then

      !$omp parallel do collapse(2)
        do k=ks, ke
        do j=js, je
        do i=is, ie
          q(i,j,k) =  this%varTmp_3d(i,j,k,varID) + this%dt * ( &
              + this%coef_b_ex(nowstage) * this%tend_buf3D_ex(i,j,k,varID,tintbuf_ind)   & 
              + this%coef_b_im(nowstage) * this%tend_buf3D_im(i,j,k,varID,tintbuf_ind)   )
        end do
        end do
        end do
      else

        !$omp parallel do collapse(2)
        do k=ks, ke
        do j=js, je
        do i=is, ie
          q(i,j,k) =  this%varTmp_3d(i,j,k,varID)                                             &
                  + this%dt * this%coef_b_ex(nowstage) * this%tend_buf3D_ex(i,j,k,varID,tintbuf_ind)
        end do
        end do
        end do
      end if    
      call PROF_rapend( 'rk_advance_generall3D', 3)

      return
    end if 

    !$omp parallel private( s ) &
    !$omp private( i,j,k )

    if ( nowstage == 1 .and. (.not. this%imex_flag) ) then
      !$omp do collapse(2)
      do k=ks, ke
      do j=js, je
      do i=is, ie
        this%var0_3D(i,j,k,varID) = q(i,j,k)
        this%varTmp_3D(i,j,k,varID) = q(i,j,k)
      end do
      end do
      end do
    end if 

    if ( this%imex_flag ) then
      !$omp do collapse(2)
      do k=ks, ke
      do j=js, je
      do i=is, ie
        q(i,j,k) = this%var0_3d(i,j,k,varID)
        this%varTmp_3d(i,j,k,varID) =  this%varTmp_3d(i,j,k,varID) + this%dt * ( &
              + this%coef_b_ex(nowstage) * this%tend_buf3D_ex(i,j,k,varID,tintbuf_ind)   & 
              + this%coef_b_im(nowstage) * this%tend_buf3D_im(i,j,k,varID,tintbuf_ind)   )
      end do
      end do
      end do
    else
      !$omp do collapse(2)
      do k=ks, ke
      do j=js, je
      do i=is, ie
        q(i,j,k) = this%var0_3d(i,j,k,varID)
        this%varTmp_3d(i,j,k,varID) =  this%varTmp_3d(i,j,k,varID)                                             &
                  + this%dt * this%coef_b_ex(nowstage) * this%tend_buf3D_ex(i,j,k,varID,tintbuf_ind)
      end do
      end do
      end do
    end if 

    if ( this%tend_buf_size == 1 .and. (.not. this%imex_flag) ) then
      !$omp do collapse(2)
      do k=ks, ke
      do j=js, je
      do i=is, ie
        q(i,j,k) = this%var0_3d(i,j,k,varID)                                                &
            +  this%dt * this%coef_a_ex(nowstage+1,nowstage)*this%tend_buf3D_ex(i,j,k,varID,1)
      end do
      end do
      end do
    else if ( .not. this%imex_flag ) then      
      do s=1, nowstage
      !$omp do collapse(2)
      do k=ks, ke
      do j=js, je
      do i=is, ie
        q(i,j,k) = q(i,j,k)                                  &
            +  this%dt * this%coef_a_ex(nowstage+1,s)*this%tend_buf3D_ex(i,j,k,varID,s)
      end do
      end do
      end do
      end do
    else ! IMEX   
      do s=1, nowstage
      !$omp do collapse(2)
      do k=ks, ke
      do j=js, je
      do i=is, ie
        q(i,j,k) = q(i,j,k)                                        &
            +  this%dt * ( this%coef_a_ex(nowstage+1,s)*this%tend_buf3D_ex(i,j,k,varID,s)  &
                         + this%coef_a_im(nowstage+1,s)*this%tend_buf3D_im(i,j,k,varID,s)  )                         
      end do
      end do
      end do
      end do
    end if

    !$omp end parallel
    call PROF_rapend( 'rk_advance_generall3D', 3)

    return
  end subroutine rk_advance_general3D

!OCL SERIAL
  subroutine rk_storeimpl_general3D( this, nowstage, q, varID, is, ie ,js, je ,ks, ke  )
    class(timeint_rk), intent(inout) :: this
    integer, intent(in) :: nowstage
    real(RP), intent(inout) :: q(:,:,:)
    integer, intent(in) :: varID
    integer, intent(in) :: is, ie ,js, je ,ks, ke 

    integer :: i,j,k
    integer :: tintbuf_ind
    !----------------------------------------    

    if (.not. this%imex_flag ) return
    
    tintbuf_ind = this%tend_buf_indmap(nowstage)   

    !$omp parallel

    if ( nowstage == 1 ) then
      !$omp do collapse(2)
      do k=ks, ke
      do j=js, je
      do i=is, ie
        this%var0_3D(i,j,k,varID) = q(i,j,k)
        this%varTmp_3D(i,j,k,varID) = q(i,j,k)
      end do
      end do
      end do
    end if
            
    !$omp do collapse(2)
    do k=ks, ke
    do j=js, je
    do i=is, ie
      q(i,j,k) = q(i,j,k)                                                                              &
            +  this%dt * this%coef_a_im(nowstage,nowstage)*this%tend_buf3D_im(i,j,k,varID,tintbuf_ind)  
    end do
    end do
    end do
    !$omp end parallel

    return
  end subroutine rk_storeimpl_general3D
 
end module scale_timeint_rk

