################################################################################
#
# Makefile for the C++ unit test of scale_sparsemat (FElib/src_cpp).
# See FElib/test/Makefile.common_cpp for the shared build recipe.
#
################################################################################

TOPDIR           = $(abspath ../../../..)
SCALEFELIBDIR    := $(TOPDIR)/FElib

BINNAME = test_sparsemat_cpp

include $(SCALEFELIBDIR)/test/Makefile.common_cpp
