################################################################################
#
# Common Makefile for each test (Please include this file)
#
################################################################################

ifeq ($(origin SYSDEP_DIR), undefined)
   SYSDEP_DIR = $(TOPDIR)/sysdep
else
   ifeq ( "$(shell ls $(SYSDEP_DIR) | grep Makedef.$(SCALE_FE_SYS))", "")
      SYSDEP_DIR=$(TOPDIR)/sysdep
   else
      USELOCALBIN = T
   endif
endif

include $(SYSDEP_DIR)/Makedef.$(SCALE_FE_SYS)
include $(TOPDIR)/Mkinclude


msg1 = "\n"

ifeq ($(SCALE_DEBUG),T)
   msg1       += "SCALE_DEBUG is set.\n"
endif

ifeq ($(SCALE_USE_SINGLEFP),T)
   msg1       += "SCALE_USE_SINGLEFP is set.\n"
endif

ifneq ($(ORG_SRCS),)
   msg1       += "User-defined file is used.\n"
   USELOCALBIN = T
endif

ifeq ($(SCALE_DISABLE_LOCALBIN),T)
   USELOCALBIN = F
endif

ifeq ($(USELOCALBIN),T)
   BUILD_DIR := $(PWD)/.libs$(POSTFIX)
   BINDIR2    = $(PWD)
   msg1      += "The location of executable files is changed to $(BINDIR2)\n"
else
   BUILD_DIR = "undefined"
   BINDIR2   = $(BINDIR)
endif

ifeq ($(origin PPNAME), undefined)
   PPNAME = scale-dg_pp(POSTFIX)
endif

ifeq ($(origin INITNAME), undefined)
   INITNAME = scale-dg_init(POSTFIX)
endif

ifeq ($(origin BINNAME), undefined)
   BINNAME = scale-dg(POSTFIX)
endif

ifeq ($(origin PPCONF), undefined)
   PPCONF = NONE
endif

ifeq ($(origin INITCONF), undefined)
   INITCONF = NONE
endif

ifeq ($(origin RUNCONF), undefined)
   RUNCONF = NONE
endif


#UTILDIR    = ${TOPDIR}/scale-rm/util/netcdf2grads_h


all: build

$(BUILD_DIR)/%.F90: $(CODE_DIR)/%.F90
	mkdir -p $(BUILD_DIR)
	cp -f $< $@

build: $(patsubst %,$(BUILD_DIR)/%,$(ORG_SRCS))
	@echo -e "$(msg1)"
	mkdir -p $(BUILD_DIR)
	$(MAKE) -C $(ATMNONHYDRO3DDIR)/src SYSDEP_DIR=$(SYSDEP_DIR) \
                                BUILD_DIR=$(BUILD_DIR)            \
                                BINDIR=$(BINDIR2)                 \
                                POSTFIX=$(POSTFIX)                \
                                FFLAG_TESTCASE=$(FFLAG_TESTCASE)

util:
	$(MAKE) -C $(UTILDIR)

run: jobshell
	$(JOBSUB) run.sh $(JOBSUB_OPTION)

jobshell: export ADDITIONAL_CONF := $(ADDITIONAL_CONF)
jobshell:
	@if [ -f $(SYSDEP_DIR)/Mkjobshell.$(SCALE_SYS).sh ]; then \
		bash $(SYSDEP_DIR)/Mkjobshell.$(SCALE_SYS).sh $(MPIEXEC) $(BINDIR2)                        \
		                                              $(PPNAME) $(INITNAME) $(BINNAME) $(SNONAME) \
		                                              $(PPCONF) $(INITCONF) $(RUNCONF) $(SNOCONF) \
		                                              $(TPROC) $(TPROC_SNO)                       \
		                                              $(DATPARAM) $(DATDISTS);                    \
	else \
		bash $(TOPDIR)/sysdep/Mkjobshell.$(SCALE_SYS).sh $(MPIEXEC) $(BINDIR2)                     \
		                                              $(PPNAME) $(INITNAME) $(BINNAME) $(SNONAME) \
		                                              $(PPCONF) $(INITCONF) $(RUNCONF) $(SNOCONF) \
		                                              $(TPROC) $(TPROC_SNO)                       \
		                                              $(DATPARAM) $(DATDISTS);                    \
	fi

vis:
	bash ./visualize/visualize.sh

eval:
	bash ./evaluate/evaluate.sh

info:
	$(MAKE) -C $(ATMNONHYDRO3DDIR)/src info \
	       BINDIR=$(BINDIR2)          \
          BUILD_DIR=$(BUILD_DIR)     \
          SYSDEP_DIR=$(SYSDEP_DIR)

.PHONY: allclean distclean clean

allclean: distclean clean
	$(MAKE) -C $(ATMNONHYDRO3DDIR)/src allclean BINDIR=$(BINDIR2)  \
                                         BUILD_DIR=$(BUILD_DIR)   \
                                         SYSDEP_DIR=$(SYSDEP_DIR)

distclean: clean
	$(MAKE) -C $(ATMNONHYDRO3DDIR)/src distclean BINDIR=$(BINDIR2)  \
                                          BUILD_DIR=$(BUILD_DIR)   \
                                          SYSDEP_DIR=$(SYSDEP_DIR)
	rm -f *.nc *LOG.pe* monitor.pe* latlon* run.sh

clean:
	$(MAKE) -C $(ATMNONHYDRO3DDIR)/src clean BINDIR=$(BINDIR2)  \
                                      BUILD_DIR=$(BUILD_DIR)   \
                                      SYSDEP_DIR=$(SYSDEP_DIR)

